"use client"

import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import * as React from "react"
import { AlertCircle, Archive, CheckCircle2, Cloud, Download, FileSpreadsheet, LoaderCircle, Plus, RefreshCw, Upload } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { requestJson } from "@/lib/mca/client"
import { ARCHIVE_CATEGORIES, IMPORTABLE_FIELDS, UPDATE_CSV_FIELDS, type ArchiveCategory, type ArchiveEntryPreview, type ImportCommitResult, type ImportPreview, type ImportSource, type LeadBatch, type MappingProfile, type UpdatePreview } from "@/lib/mca/imports/contracts"
import type { MembershipSummary } from "@/lib/mca/types"

interface Registry { sources: ImportSource[]; batches: LeadBatch[]; profiles: MappingProfile[] }
interface ApiFailure { error?: { message?: string } }

async function multipart<T>(url:string,form:FormData):Promise<T>{const response=await fetch(url,{method:"POST",body:form});const payload=await response.json() as T&ApiFailure;if(!response.ok)throw new Error(payload.error?.message??"The request failed.");return payload}

export function ImportPanel(){
  const[registry,setRegistry]=React.useState<Registry|null>(null),[members,setMembers]=React.useState<MembershipSummary[]>([]),[error,setError]=React.useState(""),[busy,setBusy]=React.useState(false)
  const[sourceId,setSourceId]=React.useState(""),[batchId,setBatchId]=React.useState(""),[newSource,setNewSource]=React.useState(""),[newSourceKind,setNewSourceKind]=React.useState<"spreadsheet"|"drive">("spreadsheet"),[newBatch,setNewBatch]=React.useState(""),[profileName,setProfileName]=React.useState("")
  const[file,setFile]=React.useState<File|null>(null),[useAi,setUseAi]=React.useState(false),[pool,setPool]=React.useState<string[]>([]),[preview,setPreview]=React.useState<ImportPreview|null>(null),[mapping,setMapping]=React.useState<Record<string,string>>({}),[originatorMapping,setOriginatorMapping]=React.useState<Record<string,string>>({}),[result,setResult]=React.useState<ImportCommitResult|null>(null)
  const[updateFile,setUpdateFile]=React.useState<File|null>(null),[updatePreview,setUpdatePreview]=React.useState<UpdatePreview|null>(null),[updateMapping,setUpdateMapping]=React.useState<Record<string,string>>({}),[updateResult,setUpdateResult]=React.useState<ImportCommitResult|null>(null)
  const[archives,setArchives]=React.useState<File[]>([]),[archivePreview,setArchivePreview]=React.useState<ArchiveEntryPreview[]>([]),[archiveRows,setArchiveRows]=React.useState<Record<string,string>>({}),[archiveCategories,setArchiveCategories]=React.useState<Record<string,ArchiveCategory>>({})
  const[drive,setDrive]=React.useState<{connected:boolean;folderName?:string;expiresAt?:string}>({connected:false}),[folderUrl,setFolderUrl]=React.useState(""),[driveFiles,setDriveFiles]=React.useState<Array<{id:string;name:string}>>([]),[driveMatches,setDriveMatches]=React.useState<ArchiveEntryPreview[]>([]),[driveRows,setDriveRows]=React.useState<Record<string,string>>({}),[driveCategories,setDriveCategories]=React.useState<Record<string,ArchiveCategory>>({})
  const load=React.useCallback(async()=>{try{const [nextRegistry,nextMembers,status]=await Promise.all([requestJson<Registry>("/api/mca/imports/registry"),requestJson<{memberships:MembershipSummary[]}>("/api/memberships"),requestJson<{connected:boolean;folderName?:string}>("/api/mca/imports/drive")]);setRegistry(nextRegistry);setMembers(nextMembers.memberships.filter((member)=>member.status==="active"));setDrive(status);setError("");if(!sourceId&&nextRegistry.sources[0])setSourceId(nextRegistry.sources[0].id)}catch(caught){setError(caught instanceof Error?caught.message:"Imports could not be loaded.")}},[sourceId])
  React.useEffect(()=>{void load()},[load])
  React.useEffect(()=>{const available=registry?.batches.filter((batch)=>batch.sourceId===sourceId)??[];if(!available.some((batch)=>batch.id===batchId))setBatchId(available[0]?.id??"")},[registry,sourceId,batchId])
  const batches=registry?.batches.filter((batch)=>batch.sourceId===sourceId)??[]

  async function createRegistry(kind:"source"|"batch"){setBusy(true);try{await requestJson("/api/mca/imports/registry",{method:"POST",body:JSON.stringify(kind==="source"?{kind,name:newSource,sourceKind:newSourceKind}:{kind,name:newBatch,sourceId})});setNewSource("");setNewBatch("");await load();toast.success(kind==="source"?"Source created":"Batch created")}catch(caught){setError(caught instanceof Error?caught.message:"Registry could not be updated.")}finally{setBusy(false)}}
  async function saveProfile(){if(!profileName.trim())return;await requestJson("/api/mca/imports/registry",{method:"POST",body:JSON.stringify({kind:"profile",name:profileName,mapping:Object.fromEntries(Object.entries(mapping).filter(([,value])=>value)),originatorMapping})});await load();toast.success("Mapping profile saved")}
  async function previewFile(override?:Record<string,string>,originators:Record<string,string>=originatorMapping){if(!file||!sourceId||!batchId)return;setBusy(true);setError("");try{const form=new FormData();form.set("file",file);form.set("sourceId",sourceId);form.set("batchId",batchId);form.set("assignmentPool",JSON.stringify(pool));form.set("originatorMapping",JSON.stringify(originators));form.set("useAiMapping",String(useAi));if(override)form.set("mapping",JSON.stringify(override));const next=await multipart<ImportPreview>("/api/mca/imports/preview",form);setPreview(next);setMapping(next.mapping);setResult(null)}catch(caught){setError(caught instanceof Error?caught.message:"Preview failed.")}finally{setBusy(false)}}
  async function reviewRow(rowId:string,decision:{duplicateDecision?:"create"|"skip";assignmentMembershipId?:string}){if(!preview)return;setBusy(true);try{const next=await requestJson<ImportPreview>(`/api/mca/imports/${preview.runId}`,{method:"PATCH",body:JSON.stringify({expectedPreviewRevision:preview.previewRevision,decisions:[{rowId,...decision}]})});setPreview(next);if(decision.assignmentMembershipId){const row=preview.rows.find((item)=>item.id===rowId);if(row?.originatorSourceValue)setOriginatorMapping((current)=>({...current,[row.originatorSourceValue!]:decision.assignmentMembershipId!}))}}catch(caught){setError(caught instanceof Error?caught.message:"Review decision could not be saved.")}finally{setBusy(false)}}
  async function commit(){if(!preview)return;setBusy(true);try{const next=await requestJson<ImportCommitResult>(`/api/mca/imports/${preview.runId}/commit`,{method:"POST",body:JSON.stringify({expectedPreviewRevision:preview.previewRevision})});setResult(next);toast.success(`${next.created} deals created`)}catch(caught){setError(caught instanceof Error?caught.message:"Commit failed.")}finally{setBusy(false)}}
  async function cancel(){if(!preview)return;await requestJson(`/api/mca/imports/${preview.runId}/cancel`,{method:"POST"});setPreview(null);setResult(null);toast.success("Import cancelled; no deals were created")}
  async function previewUpdate(override?:Record<string,string>){if(!updateFile||!sourceId||!batchId)return;setBusy(true);try{const form=new FormData();form.set("file",updateFile);form.set("sourceId",sourceId);form.set("batchId",batchId);if(override)form.set("mapping",JSON.stringify(override));const next=await multipart<UpdatePreview>("/api/mca/imports/update/preview",form);setUpdatePreview(next);setUpdateMapping(next.mapping);setUpdateResult(null)}catch(caught){setError(caught instanceof Error?caught.message:"Update preview failed.")}finally{setBusy(false)}}
  async function commitUpdate(){if(!updatePreview)return;setBusy(true);try{setUpdateResult(await requestJson<ImportCommitResult>(`/api/mca/imports/update/${updatePreview.runId}/commit`,{method:"POST",body:JSON.stringify({expectedPreviewRevision:updatePreview.previewRevision})}))}catch(caught){setError(caught instanceof Error?caught.message:"Update commit failed.")}finally{setBusy(false)}}
  async function previewArchives(){if(!preview||!archives.length)return;setBusy(true);try{const form=new FormData();form.set("runId",preview.runId);archives.forEach((file)=>form.append("archives",file));const items=await multipart<ArchiveEntryPreview[]>("/api/mca/imports/archives/preview",form);setArchivePreview(items);setArchiveRows(Object.fromEntries(items.filter((item)=>item.state==="exact").map((item)=>[`${item.archiveName}\0${item.path}`,item.candidateRowIds[0]])));setArchiveCategories(Object.fromEntries(items.map((item)=>[`${item.archiveName}\0${item.path}`,item.category])))}catch(caught){setError(caught instanceof Error?caught.message:"Archive preview failed.")}finally{setBusy(false)}}
  async function applyArchives(){if(!preview)return;setBusy(true);try{const confirmations=archivePreview.flatMap((item)=>{const key=`${item.archiveName}\0${item.path}`,rowId=archiveRows[key];return rowId?[{archiveName:item.archiveName,path:item.path,rowId,category:archiveCategories[key]??item.category}]:[]});const form=new FormData();form.set("runId",preview.runId);form.set("confirmations",JSON.stringify(confirmations));archives.forEach((file)=>form.append("archives",file));const outcome=await multipart<{stored:number;enriched:number;warnings:string[]}>("/api/mca/imports/archives/apply",form);toast.success(`${outcome.stored} documents stored`);if(outcome.warnings.length)setError(outcome.warnings.join(" "))}catch(caught){setError(caught instanceof Error?caught.message:"Documents could not be applied.")}finally{setBusy(false)}}
  async function connect(){setBusy(true);try{const outcome=await requestJson<{authorizationUrl:string}>("/api/mca/imports/drive",{method:"POST",body:JSON.stringify({action:"oauth_start",folderUrl})});window.location.assign(outcome.authorizationUrl)}catch(caught){setError(caught instanceof Error?caught.message:"Google Drive authorization could not start.");setBusy(false)}}
  async function drivePreview(){setBusy(true);try{const outcome=await requestJson<{preview:ImportPreview;files:Array<{id:string;name:string}>;matches:ArchiveEntryPreview[]}>("/api/mca/imports/drive",{method:"POST",body:JSON.stringify({action:"preview",sourceId,batchId,assignmentPool:pool,useAiMapping:useAi})});setPreview(outcome.preview);setMapping(outcome.preview.mapping);setDriveFiles(outcome.files);setDriveMatches(outcome.matches);setDriveRows(Object.fromEntries(outcome.matches.filter((item)=>item.state==="exact").map((item)=>[item.path,item.candidateRowIds[0]])));setDriveCategories(Object.fromEntries(outcome.matches.map((item)=>[item.path,item.category])));toast.success("Drive package staged") }catch(caught){setError(caught instanceof Error?caught.message:"Drive preview failed.")}finally{setBusy(false)}}
  async function applyDrive(){if(!preview)return;setBusy(true);try{const confirmations=driveMatches.flatMap((item)=>{const rowId=driveRows[item.path],file=driveFiles.find((candidate)=>candidate.name===item.path);return rowId&&file?[{fileId:file.id,rowId,category:driveCategories[item.path]??item.category}]:[]});const outcome=await requestJson<{results:Array<{state:string}>}>("/api/mca/imports/drive",{method:"POST",body:JSON.stringify({action:"apply",runId:preview.runId,confirmations})});toast.success(`${outcome.results.filter((item)=>item.state==="downloaded").length} Drive documents transferred`)}catch(caught){setError(caught instanceof Error?caught.message:"Drive documents could not be transferred.")}finally{setBusy(false)}}

  if(error&&!registry)return <Card><CardContent className="flex items-center gap-3 py-8"><AlertCircle className="text-destructive"/><div className="flex-1"><p className="font-medium">Import tools unavailable</p><p className="text-sm text-muted-foreground">{error}</p></div><Button variant="outline" onClick={()=>void load()}><RefreshCw/>Retry</Button></CardContent></Card>
  if(!registry)return <div className="flex items-center gap-2 py-8 text-sm text-muted-foreground"><LoaderCircle className="animate-spin"/>Loading import tools…</div>
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileSpreadsheet className="size-5"/>Import center</CardTitle><CardDescription>Import merchant data from CSV or Excel, review every row, then confirm your changes.</CardDescription></CardHeader><CardContent className="space-y-5">
    {error&&<div role="alert" className="flex gap-2 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive"><AlertCircle className="size-4 shrink-0"/>{error}<button className="ml-auto" onClick={()=>setError("")}>Dismiss</button></div>}
    <div className="grid gap-3 rounded-lg border p-3 md:grid-cols-2"><div className="space-y-1.5"><Label>Existing source</Label><Select value={sourceId} onValueChange={setSourceId}><SelectTrigger><SelectValue placeholder="Choose source"/></SelectTrigger><SelectContent>{registry.sources.filter((item)=>item.active).map((item)=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Lead batch</Label><Select value={batchId} onValueChange={setBatchId}><SelectTrigger><SelectValue placeholder="Choose batch"/></SelectTrigger><SelectContent>{batches.map((item)=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="flex gap-2"><Input aria-label="New source name" placeholder="New source" value={newSource} onChange={(e)=>setNewSource(e.target.value)}/><Select value={newSourceKind} onValueChange={(value)=>setNewSourceKind(value as "spreadsheet"|"drive")}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="spreadsheet">Spreadsheet</SelectItem><SelectItem value="drive">Drive</SelectItem></SelectContent></Select><Button type="button" variant="outline" disabled={!newSource.trim()||busy} onClick={()=>void createRegistry("source")}><Plus/>Source</Button></div><div className="flex gap-2"><Input aria-label="New batch name" placeholder="New batch" value={newBatch} onChange={(e)=>setNewBatch(e.target.value)}/><Button type="button" variant="outline" disabled={!sourceId||!newBatch.trim()||busy} onClick={()=>void createRegistry("batch")}><Plus/>Batch</Button></div></div>
    <Tabs defaultValue="create"><TabsList className="grid w-full grid-cols-3"><TabsTrigger value="create">Create</TabsTrigger><TabsTrigger value="update">Update</TabsTrigger><TabsTrigger value="drive">Drive</TabsTrigger></TabsList>
      <TabsContent value="create" className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="import-file">CSV or Excel · up to 1,000 rows and 25 MiB</Label><Input id="import-file" type="file" accept=".csv,.xlsx,.xls,text/csv" onChange={(e)=>setFile(e.target.files?.[0]??null)}/></div><div className="space-y-1.5"><Label htmlFor="rep-pool">Round-robin pool</Label><select id="rep-pool" multiple className="min-h-24 w-full rounded-md border bg-background p-2 text-sm" value={pool} onChange={(e)=>setPool([...e.currentTarget.selectedOptions].map((option)=>option.value))}>{members.map((member)=><option key={member.id} value={member.id}>{member.name}</option>)}</select></div></div><div className="flex flex-wrap items-center gap-3"><Switch id="ai-map" checked={useAi} onCheckedChange={setUseAi}/><Label htmlFor="ai-map">Ask configured AI provider for mapping suggestions</Label><Button disabled={!file||!sourceId||!batchId||busy} onClick={()=>void previewFile()}>{busy?<LoaderCircle className="animate-spin"/>:<Upload/>}Preview rows</Button></div>
        {preview&&<div className="space-y-4"><p className="rounded border p-3 text-sm" aria-label="Import preview counts">{preview.rows.filter((row)=>!row.errors.length&&row.duplicateDecision==="create"&&!row.warnings.some((warning)=>warning.startsWith("Resolve the source originator"))).length} create · {preview.rows.filter((row)=>row.duplicateDecision==="skip").length} skip · {preview.rows.filter((row)=>row.duplicateDealIds.length||row.warnings.some((warning)=>warning.startsWith("Possible duplicate of file row"))).length} possible duplicates · {preview.rows.filter((row)=>row.errors.length).length} errors</p><div className="rounded-lg border p-3"><div className="flex items-center justify-between"><p className="font-medium">Mapping review · {preview.mappingProvider}</p><span className="text-xs text-muted-foreground">Revision {preview.previewRevision}</span></div><div className="mt-3 grid gap-2 md:grid-cols-2">{Object.keys(preview.rows[0]?.sourceValues??{}).map((header)=><div className="grid grid-cols-[1fr_1fr] items-center gap-2" key={header}><span className="truncate text-sm">{header}{preview.mappingConfidence[header]!==undefined?` · ${Math.round(preview.mappingConfidence[header]*100)}%`:""}</span><Select value={mapping[header]??"unmapped"} onValueChange={(value)=>setMapping({...mapping,[header]:value==="unmapped"?"":value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unmapped">Do not import</SelectItem>{IMPORTABLE_FIELDS.map((field)=><SelectItem value={field} key={field}>{field}</SelectItem>)}</SelectContent></Select></div>)}</div><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void previewFile(Object.fromEntries(Object.entries(mapping).filter(([,value])=>value)))}><RefreshCw/>Apply mapping</Button><Select value="choose" onValueChange={(id)=>{const profile=registry.profiles.find((item)=>item.id===id);if(profile){setMapping(profile.mapping);setOriginatorMapping(profile.originatorMapping);void previewFile(profile.mapping,profile.originatorMapping)}}}><SelectTrigger className="w-48"><SelectValue placeholder="Load profile"/></SelectTrigger><SelectContent><SelectItem value="choose">Load mapping profile</SelectItem>{registry.profiles.map((profile)=><SelectItem value={profile.id} key={profile.id}>{profile.name}</SelectItem>)}</SelectContent></Select><Input className="w-48" aria-label="Mapping profile name" placeholder="Profile name" value={profileName} onChange={(e)=>setProfileName(e.target.value)}/><Button variant="outline" disabled={!profileName.trim()} onClick={()=>void saveProfile()}>Save profile</Button></div>{preview.mappingWarnings.map((warning)=><p className="mt-2 text-xs text-amber-700" key={warning}>{warning}</p>)}</div>
          <div className="rounded-lg border"><Table className="w-full text-left text-sm"><TableHeader><TableRow><TableHead>Row</TableHead><TableHead>Business</TableHead><TableHead>Originator</TableHead><TableHead>Duplicate decision</TableHead><TableHead>Review</TableHead></TableRow></TableHeader><TableBody>{preview.rows.map((row)=><TableRow className="align-top" key={row.id}><TableCell>{row.rowNumber}</TableCell><TableCell>{row.application.legalName??row.application.dbaName??"—"}</TableCell><TableCell className="min-w-48">{row.originatorSourceValue?<Select value={row.assignmentMembershipId??"unresolved"} onValueChange={(value)=>value!=="unresolved"&&void reviewRow(row.id,{assignmentMembershipId:value})}><SelectTrigger aria-label={`Originator for row ${row.rowNumber}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unresolved">Resolve “{row.originatorSourceValue}”</SelectItem>{members.map((member)=><SelectItem key={member.id} value={member.id}>{member.name}</SelectItem>)}</SelectContent></Select>:members.find((member)=>member.id===row.assignmentMembershipId)?.name??"Unassigned"}</TableCell><TableCell className="min-w-40">{(row.duplicateDealIds.length||row.warnings.some((warning)=>warning.startsWith("Possible duplicate of file row")))&&!row.warnings.some((warning)=>warning.startsWith("Skipped because this EIN"))?<Select value={row.duplicateDecision??"review"} onValueChange={(value)=>value!=="review"&&void reviewRow(row.id,{duplicateDecision:value as "create"|"skip"})}><SelectTrigger aria-label={`Duplicate decision for row ${row.rowNumber}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="review">Review required</SelectItem><SelectItem value="create">Create anyway</SelectItem><SelectItem value="skip">Skip row</SelectItem></SelectContent></Select>:row.warnings.some((warning)=>warning.startsWith("Skipped because this EIN"))?"Skip · same EIN":"No match"}</TableCell><TableCell className="text-xs">{[...row.errors,...row.warnings].join(" ")||"Ready"}</TableCell></TableRow>)}</TableBody></Table></div><div className="flex gap-2"><Button disabled={busy||result?.state==="completed"} onClick={()=>void commit()}><CheckCircle2/>{result?.state==="failed"?"Retry failed rows":"Commit ready rows"}</Button><Button variant="outline" disabled={busy||Boolean(result)} onClick={()=>void cancel()}>Cancel preview</Button></div>{result&&<Result result={result}/>}</div>}
        {preview&&result?.state==="completed"&&<div className="space-y-3 rounded-lg border p-3"><div><p className="font-medium">ZIP document matching</p><p className="text-xs text-muted-foreground">Only confirmed row, file, and category associations are stored.</p></div><Input type="file" accept=".zip" multiple onChange={(e)=>setArchives([...e.currentTarget.files??[]])}/><Button variant="outline" disabled={!archives.length||busy} onClick={()=>void previewArchives()}><Archive/>Inventory archives</Button>{archivePreview.map((item)=>{const key=`${item.archiveName}\0${item.path}`;return <div key={key} className="grid gap-2 rounded border p-2 text-sm md:grid-cols-[1fr_180px_180px]"><span className="truncate">{item.path} · {item.state}</span><Select value={archiveRows[key]??"unmatched"} onValueChange={(value)=>setArchiveRows({...archiveRows,[key]:value==="unmatched"?"":value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unmatched">Leave unmatched</SelectItem>{preview.rows.map((row)=><SelectItem key={row.id} value={row.id}>{row.application.legalName??row.application.dbaName??`Row ${row.rowNumber}`}</SelectItem>)}</SelectContent></Select><Select value={archiveCategories[key]??item.category} onValueChange={(value)=>setArchiveCategories({...archiveCategories,[key]:value as ArchiveCategory})}><SelectTrigger aria-label={`Category for ${item.path}`}><SelectValue/></SelectTrigger><SelectContent>{ARCHIVE_CATEGORIES.map((category)=><SelectItem key={category} value={category}>{category.split("_").join(" ")}</SelectItem>)}</SelectContent></Select></div>})}{archivePreview.length>0&&<Button onClick={()=>void applyArchives()}>Store confirmed documents</Button>}</div>}
      </TabsContent>
      <TabsContent value="update" className="space-y-4"><div className="flex flex-wrap items-center gap-3"><Button variant="outline" asChild><a href="/api/mca/imports/update/template"><Download/>Download template</a></Button><Input className="max-w-sm" type="file" accept=".csv,text/csv" onChange={(e)=>setUpdateFile(e.target.files?.[0]??null)}/><Button disabled={!updateFile||!sourceId||!batchId||busy} onClick={()=>void previewUpdate()}>Preview changes</Button></div>{updatePreview&&<><div className="rounded border p-3"><p className="font-medium">Update column mapping</p><div className="mt-2 grid gap-2 md:grid-cols-2">{updatePreview.headers.map((header)=><div className="grid grid-cols-2 items-center gap-2" key={header}><span className="truncate text-sm">{header}</span><Select value={updateMapping[header]??"unmapped"} onValueChange={(value)=>setUpdateMapping({...updateMapping,[header]:value==="unmapped"?"":value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unmapped">Do not update</SelectItem>{UPDATE_CSV_FIELDS.map((field)=><SelectItem value={field} key={field}>{field}</SelectItem>)}</SelectContent></Select></div>)}</div><Button className="mt-3" variant="outline" onClick={()=>void previewUpdate(Object.fromEntries(Object.entries(updateMapping).filter(([,value])=>value)))}><RefreshCw/>Apply update mapping</Button></div><div className="max-h-80 overflow-auto rounded border p-3 text-sm">{updatePreview.rows.map((row)=><div key={row.id} className="border-b py-2 last:border-0"><p className="font-medium">Row {row.rowNumber} · {row.dealId||"Missing ID"} · expected v{row.expectedVersion}</p>{row.errors.length?<p className="text-destructive">{row.errors.join(" ")}</p>:<div className="mt-1 grid gap-1">{Object.entries(row.changes).map(([field,value])=><p key={field}><span className="font-medium">{field}:</span> {String(row.before[field]??"blank")} → {value===null?"clear":String(value)}</p>)}{row.status&&<p><span className="font-medium">status:</span> {String(row.before.status??"unknown")} → {row.status}</p>}{!Object.keys(row.changes).length&&!row.status&&<p className="text-muted-foreground">No field changes</p>}</div>}</div>)}</div><Button disabled={busy||updateResult?.state==="completed"} onClick={()=>void commitUpdate()}>{updateResult?.state==="failed"?"Retry failed updates":"Commit updates"}</Button>{updateResult&&<Result result={updateResult}/>}</>}</TabsContent>
      <TabsContent value="drive" className="space-y-4">{drive.connected?<><div className="flex flex-wrap items-center gap-3 rounded border p-3"><Cloud className="text-emerald-600"/><div className="flex-1"><p className="font-medium">Connected to {drive.folderName}</p><p className="text-xs text-muted-foreground">OAuth refresh, server listing, bounded downloads, and per-file checkpoints are enabled{drive.expiresAt?` · access token renews after ${new Date(drive.expiresAt).toLocaleTimeString()}`:""}.</p></div><Button disabled={!sourceId||!batchId||busy} onClick={()=>void drivePreview()}>Preview package</Button><Button variant="outline" onClick={async()=>{await requestJson("/api/mca/imports/drive",{method:"DELETE"});setDrive({connected:false})}}>Revoke</Button></div>{driveMatches.length>0&&preview&&<div className="space-y-2 rounded border p-3"><p className="font-medium">Drive document review</p>{driveMatches.map((item)=><div className="grid gap-2 md:grid-cols-[1fr_220px_180px]" key={item.path}><span className="truncate text-sm">{item.path} · {item.state}</span><Select value={driveRows[item.path]??"unmatched"} onValueChange={(value)=>setDriveRows({...driveRows,[item.path]:value==="unmatched"?"":value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unmatched">Leave unmatched</SelectItem>{preview.rows.map((row)=><SelectItem key={row.id} value={row.id}>{row.application.legalName??row.application.dbaName??`Row ${row.rowNumber}`}</SelectItem>)}</SelectContent></Select><Select value={driveCategories[item.path]??item.category} onValueChange={(value)=>setDriveCategories({...driveCategories,[item.path]:value as ArchiveCategory})}><SelectTrigger aria-label={`Drive category for ${item.path}`}><SelectValue/></SelectTrigger><SelectContent>{ARCHIVE_CATEGORIES.map((category)=><SelectItem key={category} value={category}>{category.split("_").join(" ")}</SelectItem>)}</SelectContent></Select></div>)}<Button disabled={result?.state!=="completed"||busy} onClick={()=>void applyDrive()}>Transfer confirmed documents</Button><p className="text-xs text-muted-foreground">Commit the staged roster in Create, then return here to transfer only confirmed files.</p></div>}</>:<div className="rounded border p-3"><div className="max-w-xl space-y-1.5"><Label>Shared folder URL</Label><Input value={folderUrl} onChange={(e)=>setFolderUrl(e.target.value)} placeholder="https://drive.google.com/drive/folders/…"/></div><Button className="mt-3" disabled={!folderUrl||busy} onClick={()=>void connect()}><Cloud/>Authorize Google Drive</Button><p className="mt-2 text-xs text-muted-foreground">Uses Google’s web-server OAuth flow with offline access and the customer-approved read-only scope. The server verifies the returned scope and folder grant, encrypts refresh credentials, and renews expired access automatically.</p></div>}</TabsContent>
    </Tabs>
  </CardContent></Card>
}

function Result({result}:{result:ImportCommitResult}){const[url,setUrl]=React.useState("");React.useEffect(()=>{const next=URL.createObjectURL(new Blob([result.resultsCsv],{type:"text/csv"}));setUrl(next);return()=>URL.revokeObjectURL(next)},[result.resultsCsv]);return <div className="flex flex-wrap items-center gap-3 rounded-lg bg-muted p-3 text-sm"><CheckCircle2 className="text-emerald-600"/><span>{result.created} succeeded · {result.skipped} skipped · {result.failed} failed</span><Button size="sm" variant="outline" asChild><a href={url} download={`${result.runId}-results.csv`}>Results CSV</a></Button></div>}
