import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from "@/components/ui/table"
import { formatBillingMoney } from "@/lib/mca/billing-display"
import type { Invoice,Payment,Adjustment,CurrencyTotal,PlatformQuery } from "@/lib/mca/platform-console"

export function PlatformSearch({query,statuses=[],financial=false}:{query:PlatformQuery;statuses?:string[];financial?:boolean}) {
  return <form className="flex flex-wrap items-end gap-3"><Label className="grid gap-2">Search<Input name="q" defaultValue={query.q} placeholder="Company, owner email or identifier" maxLength={200}/></Label>{statuses.length>0&&<Label className="grid gap-2">Status<select name="status" defaultValue={query.status} className="h-9 rounded-md border bg-background px-3"><option value="">All statuses</option>{statuses.map(status=><option key={status} value={status}>{status.replaceAll("_"," ").replace("access:","Access: ")}</option>)}</select></Label>}{financial&&<><Label className="grid gap-2">Currency<Input name="currency" defaultValue={query.currency??""} placeholder="All (e.g. USD)" pattern="[A-Za-z]{3}" maxLength={3}/></Label><Label className="grid gap-2">From (UTC)<Input type="date" name="from" defaultValue={query.from??""}/></Label><Label className="grid gap-2">Through (UTC)<Input type="date" name="to" defaultValue={query.to??""}/></Label></>}<Button type="submit">Search</Button></form>
}
export function PlatformPagination({query,count}:{query:PlatformQuery;count:number}) {
  const url=(offset:number)=>`?${new URLSearchParams({q:query.q,status:query.status,offset:String(offset),currency:query.currency??"",from:query.from??"",to:query.to??""})}`
  return <nav aria-label="Results pages" className="flex items-center gap-4 text-sm">{query.offset>0&&<Link className="underline" href={url(Math.max(0,query.offset-50))}>Previous</Link>}<span>Page {Math.floor(query.offset/50)+1} · Up to 50 records per list</span>{count===50&&<Link className="underline" href={url(query.offset+50)}>Next</Link>}</nav>
}
export function CurrencyTotals({totals,query,companyScoped=false}:{totals:CurrencyTotal[];query?:PlatformQuery;companyScoped?:boolean}) {
  return <section className="space-y-3"><h2 className="text-lg font-semibold">Accounting totals by currency</h2><p className="text-sm text-muted-foreground">{query?.from||query?.to?`${query.from||"Beginning"} through ${query.to||"present"} (UTC).`:"All time."} {companyScoped?"This company only":"All companies"}; currency/date filters apply, text and invoice-status filters do not. Gross collected uses invoice paid date (creation date when unavailable). Invoiced and outstanding use invoice creation date; outstanding includes open invoices only. Refunds and disputes use their creation date. These are separate categories, not net revenue.</p>{totals.length===0?<p>No financial records in this range.</p>:<Table><TableHeader><TableRow><TableHead>Currency</TableHead><TableHead>Invoiced</TableHead><TableHead>Gross collected</TableHead><TableHead>Successful refunds</TableHead><TableHead>Outstanding (open)</TableHead><TableHead>Disputes (all statuses)</TableHead></TableRow></TableHeader><TableBody>{totals.map(total=><TableRow key={total.currency}><TableCell>{total.currency.toUpperCase()}</TableCell><TableCell>{formatBillingMoney(total.due,total.currency)}</TableCell><TableCell>{formatBillingMoney(total.paid,total.currency)}</TableCell><TableCell>{formatBillingMoney(total.refunded,total.currency)}</TableCell><TableCell>{formatBillingMoney(total.remaining,total.currency)}</TableCell><TableCell>{formatBillingMoney(total.disputed,total.currency)}</TableCell></TableRow>)}</TableBody></Table>}</section>
}
export function AdjustmentTable({rows}:{rows:Adjustment[]}) {return <section className="space-y-3"><h2 className="text-lg font-semibold">Refunds & disputes</h2><p className="text-sm text-muted-foreground">Observed provider adjustments, shown independently of invoice debt. Pending/failed refunds are not included in successful-refund totals.</p>{!rows.length?<p className="text-muted-foreground">No matching refunds or disputes.</p>:<Table><TableHeader><TableRow><TableHead>Company / adjustment</TableHead><TableHead>Kind</TableHead><TableHead>Status</TableHead><TableHead>Amount</TableHead><TableHead>Reason</TableHead><TableHead>Mode / created</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id}><TableCell><Link className="underline" href={`/platform/companies/${row.workspace_id}`}>{row.company_name}</Link><div className="text-xs text-muted-foreground">{row.id}</div></TableCell><TableCell>{row.kind}</TableCell><TableCell>{row.status}</TableCell><TableCell>{formatBillingMoney(row.amount,row.currency)}</TableCell><TableCell>{row.reason??"—"}</TableCell><TableCell>{row.livemode?"Live":"Test"} · {new Date(row.created_at).toLocaleDateString("en-US")}</TableCell></TableRow>)}</TableBody></Table>}</section>}
export function InvoiceTable({rows}:{rows:Invoice[]}) {return <section className="space-y-3"><h2 className="text-lg font-semibold">Invoices</h2>{!rows.length?<p className="text-muted-foreground">No matching invoices.</p>:<Table><TableHeader><TableRow><TableHead>Company / invoice</TableHead><TableHead>Status</TableHead><TableHead>Due</TableHead><TableHead>Paid</TableHead><TableHead>Remaining</TableHead><TableHead>Created</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.stripe_invoice_id}><TableCell><Link className="underline" href={`/platform/companies/${row.workspace_id}`}>{row.company_name}</Link><div className="text-xs text-muted-foreground">{row.invoice_url?<a href={row.invoice_url} target="_blank" rel="noopener noreferrer" className="underline">{row.stripe_invoice_id} ↗</a>:row.stripe_invoice_id}</div></TableCell><TableCell>{row.status}</TableCell><TableCell>{formatBillingMoney(row.amount_due,row.currency)}</TableCell><TableCell>{formatBillingMoney(row.amount_paid,row.currency)}</TableCell><TableCell>{formatBillingMoney(row.amount_remaining,row.currency)}</TableCell><TableCell>{new Date(row.created_at).toLocaleDateString("en-US")}</TableCell></TableRow>)}</TableBody></Table>}</section>}
export function PaymentTable({rows}:{rows:Payment[]}) {return <section className="space-y-3"><h2 className="text-lg font-semibold">Payments</h2><p className="text-sm text-muted-foreground">Observed payment records; invoice status filters apply only to invoices.</p>{!rows.length?<p className="text-muted-foreground">No matching payments.</p>:<Table><TableHeader><TableRow><TableHead>Company</TableHead><TableHead>Payment / invoice</TableHead><TableHead>Status</TableHead><TableHead>Paid</TableHead><TableHead>Last synced</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.stripe_payment_id}><TableCell><Link className="underline" href={`/platform/companies/${row.workspace_id}`}>{row.company_name}</Link></TableCell><TableCell className="text-xs">{row.stripe_payment_id}<br/>{row.stripe_invoice_id}</TableCell><TableCell>{row.status}</TableCell><TableCell>{formatBillingMoney(row.amount_paid,row.currency)}</TableCell><TableCell>{new Date(row.synced_at).toLocaleString("en-US")}</TableCell></TableRow>)}</TableBody></Table>}</section>}
