import { check, index, integer, pgTable, text, unique, uniqueIndex } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

export const mca_offers = pgTable("mca_offers", {
  id: text().primaryKey().notNull(),
  workspace_id: text().notNull(),
  deal_id: text().notNull(),
  submission_id: text(),
  funder_id: text(),
  funder_name: text().notNull(),
  source: text().notNull(),
  external_id: text(),
  current_revision_id: text(),
  created_by_user_id: text(),
  created_at: text().notNull(),
  updated_at: text().notNull(),
}, (table) => [
  index("mca_offers_deal_idx").on(table.workspace_id, table.deal_id, table.created_at),
  unique("mca_offers_workspace_id_id_key").on(table.workspace_id, table.id),
  uniqueIndex("mca_offers_external_unique").on(table.workspace_id, table.source, table.external_id).where(sql`external_id IS NOT NULL`),
  check("mca_offers_source_check", sql`source IN ('api','email','link','manual','historical')`),
])

export const mca_offer_revisions = pgTable("mca_offer_revisions", {
  id: text().primaryKey().notNull(),
  workspace_id: text().notNull(),
  offer_id: text().notNull(),
  revision_number: integer().notNull(),
  state: text().notNull(),
  product: text(),
  amount_cents: integer(),
  factor_rate_millionths: integer(),
  buy_rate_millionths: integer(),
  term_months: integer(),
  payment_amount_cents: integer(),
  payment_frequency: text(),
  fee_cents: integer(),
  commission_cents: integer(),
  stipulations_json: text().default("[]").notNull(),
  incomplete_fields_json: text().default("[]").notNull(),
  effective_at: text().notNull(),
  created_by_user_id: text(),
  created_at: text().notNull(),
}, (table) => [
  unique("mca_offer_revisions_offer_number_key").on(table.workspace_id, table.offer_id, table.revision_number),
  unique("mca_offer_revisions_workspace_id_id_key").on(table.workspace_id, table.id),
  index("mca_offer_revisions_offer_idx").on(table.workspace_id, table.offer_id, table.revision_number),
  check("mca_offer_revisions_state_check", sql`state IN ('active','withdrawn','superseded','funded')`),
  check("mca_offer_revisions_amount_check", sql`amount_cents IS NULL OR amount_cents > 0`),
  check("mca_offer_revisions_money_check", sql`(payment_amount_cents IS NULL OR payment_amount_cents >= 0) AND (fee_cents IS NULL OR fee_cents >= 0) AND (commission_cents IS NULL OR commission_cents >= 0)`),
])

export const mca_offer_selections = pgTable("mca_offer_selections", {
  id: text().primaryKey().notNull(),
  workspace_id: text().notNull(),
  deal_id: text().notNull(),
  offer_id: text().notNull(),
  offer_revision_id: text().notNull(),
  active: integer().default(1).notNull(),
  selected_by_user_id: text(),
  selected_at: text().notNull(),
  deselected_by_user_id: text(),
  deselected_at: text(),
  reason: text(),
}, (table) => [
  index("mca_offer_selections_deal_idx").on(table.workspace_id, table.deal_id, table.active),
  uniqueIndex("mca_offer_selections_active_offer_unique").on(table.workspace_id, table.deal_id, table.offer_id).where(sql`active = 1`),
  check("mca_offer_selections_active_check", sql`active IN (0, 1)`),
])

export const mca_manual_submissions = pgTable("mca_manual_submissions", {
  id: text().primaryKey().notNull(),
  workspace_id: text().notNull(),
  deal_id: text().notNull(),
  funder_id: text(),
  funder_name: text().notNull(),
  historical_at: text().notNull(),
  reason: text().notNull(),
  state: text().notNull(),
  offer_id: text(),
  source: text().default("manual").notNull(),
  idempotency_key: text().notNull(),
  created_by_user_id: text(),
  created_at: text().notNull(),
  updated_at: text().notNull(),
}, (table) => [
  unique("mca_manual_submissions_idempotency_key").on(table.workspace_id, table.idempotency_key),
  index("mca_manual_submissions_deal_idx").on(table.workspace_id, table.deal_id, table.historical_at),
  check("mca_manual_submissions_state_check", sql`state IN ('submitted','approved','funded')`),
  check("mca_manual_submissions_source_check", sql`source IN ('manual','historical')`),
])

export const mca_advances = pgTable("mca_advances", {
  id: text().primaryKey().notNull(),
  workspace_id: text().notNull(),
  funding_event_id: text().notNull(),
  deal_id: text().notNull(),
  offer_id: text().notNull(),
  offer_revision_id: text().notNull(),
  funded_at: text().notNull(),
  principal_cents: integer().notNull(),
  payback_cents: integer(),
  periodic_payment_cents: integer(),
  payment_count: integer(),
  payment_frequency: text(),
  calendar_convention: text(),
  commission_cents: integer().default(0).notNull(),
  fee_cents: integer().default(0).notNull(),
  expected_commission_at: text(),
  expected_fee_at: text(),
  source: text().notNull(),
  calculation_snapshot_json: text().default("{}").notNull(),
  status: text().default("active").notNull(),
  status_version: integer().default(1).notNull(),
  correction_of_advance_id: text(),
  reversed_at: text(),
  created_at: text().notNull(),
  updated_at: text().notNull(),
}, (table) => [
  unique("mca_advances_funding_event_key").on(table.workspace_id, table.funding_event_id),
  unique("mca_advances_offer_revision_key").on(table.workspace_id, table.offer_revision_id),
  index("mca_advances_deal_idx").on(table.workspace_id, table.deal_id, table.funded_at),
  check("mca_advances_source_check", sql`source IN ('live','manual','historical')`),
  check("mca_advances_status_check", sql`status IN ('active','reversed','corrected')`),
  check("mca_advances_money_check", sql`principal_cents > 0 AND commission_cents >= 0 AND fee_cents >= 0 AND (payback_cents IS NULL OR payback_cents >= principal_cents) AND (periodic_payment_cents IS NULL OR periodic_payment_cents > 0) AND (payment_count IS NULL OR payment_count > 0)`),
])

export const mca_funding_events = pgTable("mca_funding_events", {
  id: text().primaryKey().notNull(),
  workspace_id: text().notNull(),
  deal_id: text().notNull(),
  offer_id: text().notNull(),
  offer_revision_id: text().notNull(),
  advance_id: text().notNull(),
  manual_submission_id: text(),
  idempotency_key: text().notNull(),
  funded_at: text().notNull(),
  amount_cents: integer().notNull(),
  commission_cents: integer().default(0).notNull(),
  fee_cents: integer().default(0).notNull(),
  expected_commission_at: text(),
  expected_fee_at: text(),
  splits_json: text().default("[]").notNull(),
  accounting_record_ids_json: text().default("[]").notNull(),
  source: text().notNull(),
  state: text().default("committed").notNull(),
  correction_of_event_id: text(),
  reversed_at: text(),
  created_by_user_id: text(),
  created_at: text().notNull(),
}, (table) => [
  unique("mca_funding_events_idempotency_key").on(table.workspace_id, table.idempotency_key),
  unique("mca_funding_events_advance_id_key").on(table.workspace_id, table.advance_id),
  index("mca_funding_events_deal_idx").on(table.workspace_id, table.deal_id, table.funded_at),
  check("mca_funding_events_source_check", sql`source IN ('live','manual','historical')`),
  check("mca_funding_events_state_check", sql`state IN ('committed','reversed','corrected')`),
])

export const mca_historical_import_runs = pgTable("mca_historical_import_runs", {
  id: text().primaryKey().notNull(),
  workspace_id: text().notNull(),
  source_id: text().notNull(),
  batch_id: text().notNull(),
  state: text().notNull(),
  preview_revision: integer().default(1).notNull(),
  totals_json: text().default("{}").notNull(),
  reconciliation_json: text().default("{}").notNull(),
  created_by_user_id: text(),
  created_at: text().notNull(),
  committed_at: text(),
}, (table) => [
  unique("mca_historical_import_runs_batch_key").on(table.workspace_id, table.source_id, table.batch_id),
  check("mca_historical_import_runs_state_check", sql`state IN ('preview','committed','failed')`),
])

export const mca_historical_import_rows = pgTable("mca_historical_import_rows", {
  id: text().primaryKey().notNull(),
  workspace_id: text().notNull(),
  run_id: text().notNull(),
  source_id: text().notNull(),
  external_id: text().notNull(),
  row_number: integer().notNull(),
  normalized_json: text().notNull(),
  validation_errors_json: text().default("[]").notNull(),
  duplicate: integer().default(0).notNull(),
  outcome: text().default("pending").notNull(),
  funding_event_id: text(),
  created_at: text().notNull(),
}, (table) => [
  unique("mca_historical_import_rows_external_key").on(table.workspace_id, table.source_id, table.external_id),
  unique("mca_historical_import_rows_run_row_key").on(table.run_id, table.row_number),
  check("mca_historical_import_rows_outcome_check", sql`outcome IN ('pending','created','duplicate','invalid')`),
])
