import { PlatformHeading, PlatformSection, PlatformStatus } from "@/components/mca/platform/presentation"
import { listDemoSubmissions, hasUnnotifiedDemoSubmissions } from "@/lib/marketing/demo-storage"
import { requirePlatformPage } from "@/lib/mca/platform-page-access"
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from "@/components/ui/table"

export default async function DemoRequestsPage() {
  await requirePlatformPage()
  const [rows, unnotified] = await Promise.all([listDemoSubmissions(), hasUnnotifiedDemoSubmissions()])
  return <div className="min-w-0 space-y-6"><PlatformHeading snapshotAt={new Date().toISOString()} title="Demo requests" description="Inbound brokerage inquiries and notification delivery status." /><div>{unnotified && <p role="status" className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-sm font-medium text-amber-800 dark:text-amber-300">Warning: one or more demo requests have unknown or unsent notification status. Review the list; retry only tracked unsent requests.</p>}</div><PlatformSection title="Request inbox">{rows.length === 0 ? <p className="py-6 text-sm text-muted-foreground">No demo requests.</p> : <Table aria-label="Demo requests"><TableHeader><TableRow><TableHead>Received</TableHead><TableHead>Brokerage</TableHead><TableHead>Contact</TableHead><TableHead>Team size</TableHead><TableHead>Message</TableHead><TableHead>Notification</TableHead></TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.request_id}><TableCell>{new Date(row.created_at).toLocaleString("en-US")}</TableCell><TableCell>{row.contact.brokerage}</TableCell><TableCell>{row.contact.name}<div><a className="underline" href={`mailto:${row.contact.email}`}>{row.contact.email}</a></div></TableCell><TableCell>{row.contact.teamSize}</TableCell><TableCell className="max-w-sm whitespace-normal">{row.contact.message || "—"}</TableCell><TableCell><PlatformStatus value={row.notification_status} /><div className="text-xs text-muted-foreground">{row.notification_attempts} attempts</div></TableCell></TableRow>)}</TableBody></Table>}</PlatformSection></div>
}
