import {randomUUID} from "node:crypto"
import {BILLING_CATALOG} from "../../src/lib/mca/billing-catalog"
import type {StripeBillingClient} from "../../src/lib/mca/billing"
export function signupStripeProvider(){
 const email=`${randomUUID()}@example.test`;const sessions=new Map<string,Record<string,unknown>>(),subs:Array<Record<string,unknown>>=[]
 const calls={setups:0,subscriptions:0,customers:0,setup:{} as Record<string,unknown>,sub:{} as Record<string,unknown>};let customer='',attachedCustomer=''
 const creations=new Map<string,Record<string,unknown>>()
 const previous=(options?:{idempotencyKey?:string})=>options?.idempotencyKey?creations.get(options.idempotencyKey):undefined
 const remember=(value:Record<string,unknown>,options?:{idempotencyKey?:string})=>{if(options?.idempotencyKey)creations.set(options.idempotencyKey,value);return value}
 const client={prices:{retrieve:async(id:string)=>({id,active:true,livemode:false,currency:'usd',unit_amount:id==='price_base'?39900:null,billing_scheme:id==='price_base'?'per_unit':'tiered',tiers_mode:'graduated',tiers:BILLING_CATALOG.additionalSeats.tiers.map(t=>({up_to:t.upTo,unit_amount:t.unitAmountCents})),recurring:{interval:'month',interval_count:1,usage_type:'licensed'}})},checkout:{sessions:{create:async(params:Record<string,unknown>,options?:{idempotencyKey?:string})=>{const existing=previous(options);if(existing)return existing;calls.setups++;calls.setup=params;const id=`cs_${randomUUID()}`;const s={id,livemode:false,mode:'setup',status:'open',url:`https://checkout.stripe.com/${id}`,metadata:params.metadata,customer_details:null,setup_intent:null};sessions.set(id,s);return remember(s,options)},retrieve:async(id:string)=>sessions.get(id)}},setupIntents:{retrieve:async()=>({id:'seti_saved',livemode:false,status:'succeeded',customer:null,payment_method:'pm_saved'})},paymentMethods:{retrieve:async()=>({id:'pm_saved',livemode:false,type:'card',customer:attachedCustomer||null,billing_details:{address:{country:'US',postal_code:'10001'}},card:{exp_month:12,exp_year:2030}}),attach:async(_id:string,p:{customer:string})=>{attachedCustomer=p.customer;return{customer:attachedCustomer}}},customers:{create:async(_params:unknown,options?:{idempotencyKey?:string})=>{const existing=previous(options);if(existing)return existing;calls.customers++;customer=`cus_${randomUUID()}`;return remember({id:customer,livemode:false},options)},update:async()=>({}),retrieve:async()=>({id:customer,livemode:false,metadata:{}})},subscriptions:{list:async()=>({data:subs,has_more:false}),retrieve:async(id:string)=>subs.find(s=>s.id===id),create:async(params:Record<string,unknown>,options?:{idempotencyKey?:string})=>{const existing=previous(options);if(existing)return existing;calls.subscriptions++;calls.sub=params;const now=Math.floor(Date.now()/1000);const s={id:`sub_${randomUUID()}`,customer,livemode:false,status:'trialing',trial_start:now,trial_end:now+14*86400,metadata:params.metadata,default_payment_method:'pm_saved',items:{data:[{id:'si_base',quantity:1,price:{id:'price_base'},current_period_start:now,current_period_end:now+14*86400}]}};subs.push(s);return remember(s,options)}},invoicePayments:{list:async()=>({data:[],has_more:false})},invoices:{list:async()=>({data:[],has_more:false})},charges:{list:async()=>({data:[],has_more:false})}} as unknown as StripeBillingClient
 function complete(){const s=[...sessions.values()].at(-1)!;Object.assign(s,{status:'complete',customer_details:{email},setup_intent:'seti_saved'});return String(s.id)}
 return{client,calls,sessions,subs,complete,email}
}
