import Link from "next/link"
import { platformCompanies,platformQuerySchema,listBillingStateExceptions } from "@/lib/mca/platform-console"
import { requirePlatformPage } from "@/lib/mca/platform-page-access"
import { PlatformSearch,PlatformPagination } from "@/components/mca/platform/tables"
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from "@/components/ui/table"
export default async function CompaniesPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  await requirePlatformPage();const query=platformQuerySchema.parse(await searchParams),[rows,exceptions]=await Promise.all([platformCompanies(query),listBillingStateExceptions()])
  return <div className="space-y-6"><h1 className="text-3xl font-bold">Companies</h1><section className="rounded-lg border p-4"><h2 className="font-semibold">Billing state exceptions ({exceptions.length})</h2><p className="text-sm text-muted-foreground">Review each missing state or explicit exemption before choosing a resolution.</p>{exceptions.map(row=><p key={row.id}><Link className="underline" href={`/platform/companies/${row.id}`}>{row.name}</Link> — {row.legacyExempt?`Legacy exempt (${row.stateKind??"historical"})`:"Missing billing state"}</p>)}</section><PlatformSearch query={query} statuses={["access:trial","access:active","access:grace","access:paused","access:extended","missing_state","no_subscription","active","past_due","unpaid","canceled","incomplete","legacy_exempt","manual_paused"]}/><p className="text-sm text-muted-foreground">Filter by current access, subscription status or explicit override. Current access includes trial and grace expiration.</p>{rows.length===0?<p>No matching companies.</p>:<Table><TableHeader><TableRow><TableHead>Company</TableHead><TableHead>Billing state</TableHead><TableHead>Access</TableHead><TableHead>Subscription</TableHead><TableHead>Selected / purchased</TableHead><TableHead>Reserved / limit</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id}><TableCell><Link className="font-medium underline" href={`/platform/companies/${row.id}`}>{row.name}</Link></TableCell><TableCell>{row.billingState.replaceAll("_"," ")}</TableCell><TableCell>{row.access.status.replaceAll("_"," ")}<div className="text-xs text-muted-foreground">{row.access.reason?.replaceAll("_"," ")}</div></TableCell><TableCell>{row.subscriptionStatus}</TableCell><TableCell>{row.selectedSeats} / {row.purchasedSeats}</TableCell><TableCell>{row.occupiedSeats} / {row.access.seatLimit}</TableCell></TableRow>)}</TableBody></Table>}<PlatformPagination query={query} count={rows.length}/></div>
}
