import test, { after, before } from "node:test"
import assert from "node:assert/strict"
import { mkdtempSync, rmSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { deflateRawSync } from "node:zlib"
import * as XLSX from "xlsx"
import { closeDatabaseForTests, getDatabase } from "../src/lib/mca/db"
import type { DealActor } from "../src/lib/mca/deals/schema"
import { applyBulkDealUpdate, createDeal, getDealForDocument, updateDealRecord } from "../src/lib/mca/deals/service"
import { inspectArchives } from "../src/lib/mca/imports/archive"
import { roundRobinAssignments } from "../src/lib/mca/imports/assignment"
import { downloadDriveFile, listDriveFolder, parseDriveFolderId, refreshDriveCredential } from "../src/lib/mca/imports/drive"
import { applyDriveDocuments, beginDriveOAuth, completeDriveOAuth } from "../src/lib/mca/imports/drive-service"
import { heuristicMapping, mapRow } from "../src/lib/mca/imports/mapping"
import { parseSpreadsheet } from "../src/lib/mca/imports/parser"
import { commitCsvUpdate, commitSpreadsheetImport, createImportSource, createLeadBatch, listImportRegistry, previewCsvUpdate, previewSpreadsheetImport, reviewSpreadsheetImport, saveMappingProfile } from "../src/lib/mca/imports/service"
import { beginCommit, driveTransfersForRun, recordDriveTransfer, recordRowResult, recordRowResultInTransaction, removeDriveConnection } from "../src/lib/mca/imports/repository"
import { createPostgresTestDatabase } from "./helpers/postgres-test-db.mjs"

const temp = mkdtempSync(join(tmpdir(), "mca-imports-"))
process.env.MCA_DATA_ENCRYPTION_KEY = Buffer.alloc(32, 9).toString("base64url")
process.env.MCA_APP_ORIGIN="https://mca.example.test"
process.env.MCA_GOOGLE_DRIVE_CLIENT_ID="client-id"
process.env.MCA_GOOGLE_DRIVE_CLIENT_SECRET="client-secret"

const ids={workspace:"20000000-0000-4000-8000-000000000001",adminUser:"20000000-0000-4000-8000-000000000002",admin:"20000000-0000-4000-8000-000000000003",repAUser:"20000000-0000-4000-8000-000000000004",repA:"20000000-0000-4000-8000-000000000005",repBUser:"20000000-0000-4000-8000-000000000006",repB:"20000000-0000-4000-8000-000000000007",otherWorkspace:"20000000-0000-4000-8000-000000000008",otherUser:"20000000-0000-4000-8000-000000000009",otherAdmin:"20000000-0000-4000-8000-000000000010"}
const actor:DealActor={workspaceId:ids.workspace,userId:ids.adminUser,membershipId:ids.admin,role:"admin",managedMembershipIds:[],activeMembershipIds:[ids.admin,ids.repA,ids.repB],source:"user",correlationId:"imports-test"}
const otherActor:DealActor={workspaceId:ids.otherWorkspace,userId:ids.otherUser,membershipId:ids.otherAdmin,role:"admin",managedMembershipIds:[],activeMembershipIds:[ids.otherAdmin],source:"user",correlationId:"imports-other"}
let testDatabase: Awaited<ReturnType<typeof createPostgresTestDatabase>>

async function seed(){const database=getDatabase(),now=new Date().toISOString(),flags=JSON.stringify({reports:true,payments:true,integrations:true}),pages=JSON.stringify({dashboard:true,deals:true,users:true,reports:true,payments:true,workspace:true,integrations:true}),actions=JSON.stringify({createDeal:true,exportDeals:true,inviteUsers:true,manageApiKeys:true,viewPaymentTable:true,viewCompanyFinancials:true});for(const [workspace,name] of [[ids.workspace,"Import Test"],[ids.otherWorkspace,"Other Test"]])await database.prepare("INSERT INTO workspaces (id,name,timezone,seat_limit,feature_flags,page_visibility,action_visibility,created_at,updated_at) VALUES (?,?,'America/New_York',10,?,?,?,?,?)").run(workspace,name,flags,pages,actions,now,now)
  for(const [userId,memberId,workspace,email,role] of [[ids.adminUser,ids.admin,ids.workspace,"admin@import.test","admin"],[ids.repAUser,ids.repA,ids.workspace,"a@import.test","rep"],[ids.repBUser,ids.repB,ids.workspace,"b@import.test","rep"],[ids.otherUser,ids.otherAdmin,ids.otherWorkspace,"admin@other.test","admin"]]){await database.prepare("INSERT INTO users (id,email,password_hash,name,phone,application_identifier,created_at,updated_at) VALUES (?,?,NULL,?,NULL,?,?,?)").run(userId,email,email,`APP-${String(userId).slice(-6)}`,now,now);await database.prepare("INSERT INTO memberships (id,workspace_id,user_id,role,manager_membership_id,status,sender_association,created_at,updated_at) VALUES (?,?,?, ?,NULL,'active',NULL,?,?)").run(memberId,workspace,userId,role,now,now)}}
before(async()=>{testDatabase=await createPostgresTestDatabase("imports_core");process.env.DATABASE_URL=testDatabase.databaseUrl;await seed()});after(async()=>{await closeDatabaseForTests();await testDatabase.close();rmSync(temp,{recursive:true,force:true})})

function workbookBytes(bookType:"xlsx"|"xls"):Uint8Array{const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([["Business Name","Revenue"],["Acme LLC",125000]]),"Merchants");return XLSX.write(workbook,{type:"buffer",bookType})}

test("parses CSV with encoding and header detection; rejects other spreadsheet formats", () => {
  const csv = parseSpreadsheet({ filename: "leads.csv", bytes: Buffer.from("Exported 2026-09-08\nBusiness Name,Revenue\nCafé Uno,100000") })
  assert.equal(csv.headerRow, 2); assert.equal(csv.rows[0][0], "Café Uno")
  const legacy = parseSpreadsheet({ filename: "leads.csv", bytes: Buffer.from("Business Name,City\nCaf\xe9,Montr\xe9al", "binary") })
  assert.equal(legacy.encoding, "windows-1252"); assert.equal(legacy.rows[0][0], "Café")
  for (const format of ["xlsx", "xls"] as const) assert.throws(() => parseSpreadsheet({ filename: `leads.${format}`, bytes: workbookBytes(format) }), /Choose a CSV/)
  assert.throws(() => parseSpreadsheet({ filename: "leads.tsv", bytes: Buffer.from("a\tb\n1\t2") }), /Choose a CSV/)
})

test("MIC-119 stages a realistic 1,000-row sheet and preserves unmapped samples",async()=>{const rows=Array.from({length:1000},(_,index)=>`Merchant ${index+1},${100000+index},note ${index+1}`);const parsed=parseSpreadsheet({filename:"1000.csv",bytes:Buffer.from(`Business Name,Monthly Revenue,Unmapped Note\n${rows.join("\n")}`)});assert.equal(parsed.rows.length,1000);const guessed=heuristicMapping(parsed.headers);const mapped=mapRow(parsed.headers,parsed.rows[999],guessed.mapping);assert.equal(mapped.application.legalName,"Merchant 1000");assert.equal(mapped.sourceValues["Unmapped Note"],"note 1000")})

test("MIC-155 round robin is stable and explicit originators do not consume the pool cursor",async()=>{assert.deepEqual(roundRobinAssignments([{},{explicitOriginator:"special"},{},{}],["a","b"]),["a","special","b","a"])})

function crc32(data:Buffer):number{let crc=0xffffffff;for(const byte of data){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return(crc^0xffffffff)>>>0}
function zip(entries:Array<{name:string;data?:Buffer;declaredSize?:number}>):Uint8Array{const locals:Buffer[]=[],centrals:Buffer[]=[];let offset=0;for(const item of entries){const name=Buffer.from(item.name),raw=item.data??Buffer.alloc(0),compressed=deflateRawSync(raw),declared=item.declaredSize??raw.length,crc=crc32(raw);const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt16LE(8,8);local.writeUInt32LE(crc,14);local.writeUInt32LE(compressed.length,18);local.writeUInt32LE(declared,22);local.writeUInt16LE(name.length,26);locals.push(local,name,compressed);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(8,10);central.writeUInt32LE(crc,16);central.writeUInt32LE(compressed.length,20);central.writeUInt32LE(declared,24);central.writeUInt16LE(name.length,28);central.writeUInt32LE(offset,42);centrals.push(central,name);offset+=local.length+name.length+compressed.length}const directory=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,directory,end])}
const archiveRows=[{id:"row-a",rowNumber:2,application:{legalName:"Acme LLC"},sourceValues:{},assignmentMembershipId:null,originatorSourceValue:null,duplicateDecision:"create" as const,errors:[],warnings:[],duplicateDealIds:[]},{id:"row-b",rowNumber:3,application:{legalName:"Acme Inc"},sourceValues:{},assignmentMembershipId:null,originatorSourceValue:null,duplicateDecision:"create" as const,errors:[],warnings:[],duplicateDealIds:[]}]
test("MIC-165 inventories exact, ambiguous and unmatched folders without inflating content",async()=>{const entries=await inspectArchives([{filename:"docs.zip",bytes:zip([{name:"Acme LLC/statement.pdf",data:Buffer.from("pdf")},{name:"Unknown/check.pdf",data:Buffer.from("check")}])}],archiveRows);assert.equal(entries[0].state,"ambiguous");assert.equal(entries[1].state,"unmatched")})
test("MIC-165 rejects traversal, nested archives and declared expansion bombs before allocation",async()=>{await assert.rejects(()=>inspectArchives([{filename:"bad.zip",bytes:zip([{name:"../secret.pdf",data:Buffer.from("x")}])}],archiveRows),(error:{code?:string})=>error.code==="unsafe_archive_path");await assert.rejects(()=>inspectArchives([{filename:"nested.zip",bytes:zip([{name:"Acme LLC/more.zip",data:Buffer.from("x")}])}],archiveRows),(error:{code?:string})=>error.code==="nested_archive");await assert.rejects(()=>inspectArchives([{filename:"bomb.zip",bytes:zip([{name:"Acme LLC/bomb.pdf",declaredSize:30*1024*1024}])}],archiveRows),(error:{code?:string})=>["archive_entry_size","archive_parse_failed"].includes(error.code??""))})

test("MIC-119/MIC-155 preview, cancellation, member invalidation and checkpointed commit",async()=>{const source=await createImportSource(actor,{name:"Broker referrals"}),batch=await createLeadBatch(actor,{sourceId:source.id,name:"September"});const cancelled=await previewSpreadsheetImport(actor,{sourceId:source.id,batchId:batch.id,filename:"cancel.csv",bytes:Buffer.from("Business Name\nNever Created LLC")});const { cancelImport }=await import("../src/lib/mca/imports/service");await cancelImport(actor,cancelled.runId);assert.equal((await commitSpreadsheetImport(actor,{runId:cancelled.runId,expectedPreviewRevision:1})).state,"cancelled");assert.equal((await getDatabase().prepare<{count:number}>("SELECT count(*)::int count FROM deals WHERE legal_name='Never Created LLC'").get())!.count,0)
  const preview=await previewSpreadsheetImport(actor,{sourceId:source.id,batchId:batch.id,filename:"leads.csv",bytes:Buffer.from("Business Name,Originator\nAlpha LLC,\nBeta LLC,\nGamma LLC,"),assignmentPool:[ids.repA,ids.repB]});assert.deepEqual(preview.rows.map((row)=>row.assignmentMembershipId),[ids.repA,ids.repB,ids.repA]);await assert.rejects(()=>commitSpreadsheetImport(actor,{runId:preview.runId,expectedPreviewRevision:2}),(error:{code?:string})=>error.code==="import_preview_stale")
  await getDatabase().prepare("UPDATE memberships SET status='deactivated' WHERE id=?").run(ids.repB);await assert.rejects(()=>commitSpreadsheetImport(actor,{runId:preview.runId,expectedPreviewRevision:1}),(error:{code?:string})=>error.code==="inactive_assignee");await getDatabase().prepare("UPDATE memberships SET status='active' WHERE id=?").run(ids.repB)
  const result=await commitSpreadsheetImport(actor,{runId:preview.runId,expectedPreviewRevision:1});assert.equal(result.created,3);const retry=await commitSpreadsheetImport(actor,{runId:preview.runId,expectedPreviewRevision:1});assert.equal(retry.created,3);assert.equal((await getDatabase().prepare<{count:number}>("SELECT count(*)::int count FROM deals WHERE legal_name IN ('Alpha LLC','Beta LLC','Gamma LLC')").get())!.count,3)})

test("MIC-119/MIC-155 persists duplicate and external-originator review, encrypts staging, and recovers an expired commit lease",async()=>{const registry=await listImportRegistry(actor),source=registry.sources[0],batch=registry.batches[0];await createDeal(actor,{idempotencyKey:"duplicate-seed",legalName:"Reviewed Duplicate LLC"});const preview=await previewSpreadsheetImport(actor,{sourceId:source.id,batchId:batch.id,filename:"review.csv",bytes:Buffer.from("Business Name,Originator\nReviewed Duplicate LLC,Outside Rep"),mapping:{"Business Name":"legalName","Originator":"originatorMembershipId"}});assert.equal(preview.rows[0].duplicateDecision,null);assert.equal(preview.rows[0].assignmentMembershipId,null);const staged=(await getDatabase().prepare("SELECT application_json,source_values_json FROM import_rows WHERE id=?").get(preview.rows[0].id)) as {application_json:string;source_values_json:string};assert.equal(staged.application_json.includes("Reviewed Duplicate"),false);assert.equal(staged.source_values_json.includes("Outside Rep"),false)
  const reviewed=await reviewSpreadsheetImport(actor,{runId:preview.runId,expectedPreviewRevision:1,decisions:[{rowId:preview.rows[0].id,duplicateDecision:"create",assignmentMembershipId:ids.repA}]});assert.equal(reviewed.previewRevision,2);assert.equal(reviewed.rows[0].assignmentMembershipId,ids.repA);const profile=await saveMappingProfile(actor,{name:"External reps",mapping:preview.mapping,originatorMapping:{"Outside Rep":ids.repA}});assert.equal(profile.originatorMapping["Outside Rep"],ids.repA);const staleWorkerToken=await beginCommit(actor.workspaceId,preview.runId,2);assert.ok(staleWorkerToken);await getDatabase().prepare("UPDATE import_runs SET lease_expires_at=? WHERE id=?").run("2000-01-01T00:00:00.000Z",preview.runId);const committed=await commitSpreadsheetImport(actor,{runId:preview.runId,expectedPreviewRevision:2});assert.equal(committed.created,1);assert.equal(await recordRowResult(actor.workspaceId,preview.runId,preview.rows[0].id,"failed",null,"late stale worker",staleWorkerToken!),false);const saved=(await getDatabase().prepare("SELECT state,deal_id FROM import_rows WHERE id=?").get(preview.rows[0].id)) as {state:string;deal_id:string};assert.equal(saved.state,"created");assert.ok(saved.deal_id)})

test("MIC-173 rejects cross-workspace/blank IDs, applies durable clears, and detects stale versions",async()=>{const source=(await listImportRegistry(actor)).sources[0],batch=(await listImportRegistry(actor)).batches[0];const foreign=(await createDeal(otherActor,{idempotencyKey:"foreign",legalName:"Foreign LLC"})).deal;const target=(await createDeal(actor,{idempotencyKey:"target",legalName:"Target LLC",contactName:"Remove Me"})).deal
  const preview=await previewCsvUpdate(actor,{sourceId:source.id,batchId:batch.id,filename:"updates.csv",bytes:Buffer.from(`dealId,expectedVersion,legalName,clearFields\n,1,Blank LLC,\n${foreign.id},1,Hacked LLC,\n${target.id},${target.version},,contactName`)});assert.match(preview.rows[0].errors.join(" "),/deal ID/i);assert.match(preview.rows[1].errors.join(" "),/authorized workspace/i);const result=await commitCsvUpdate(actor,{runId:preview.runId,expectedPreviewRevision:1});assert.equal(result.created,1);assert.equal((await getDealForDocument(actor,target.id)).contactName,undefined)
  const stale=await previewCsvUpdate(actor,{sourceId:source.id,batchId:batch.id,filename:"stale.csv",bytes:Buffer.from(`dealId,expectedVersion,legalName\n${target.id},${(await getDealForDocument(actor,target.id)).version},Changed`)});const current=await getDealForDocument(actor,target.id);await updateDealRecord(actor,target.id,{expectedVersion:current.version,industry:"Retail"});const staleResult=await commitCsvUpdate(actor,{runId:stale.runId,expectedPreviewRevision:1});assert.equal(staleResult.failed,1);assert.equal((await getDealForDocument(actor,target.id)).legalName,"Target LLC")})

test("MIC-173 applies fields and status atomically in one version and does not reapply a completed retry",async()=>{const source=(await listImportRegistry(actor)).sources[0],batch=(await listImportRegistry(actor)).batches[0],target=(await createDeal(actor,{idempotencyKey:"atomic-update",legalName:"Atomic LLC"})).deal;const preview=await previewCsvUpdate(actor,{sourceId:source.id,batchId:batch.id,filename:"atomic.csv",bytes:Buffer.from(`Deal,Version,Name,Stage\n${target.id},${target.version},Atomic Renamed LLC,new_application`),mapping:{Deal:"dealId",Version:"expectedVersion",Name:"legalName",Stage:"status"}});assert.equal(preview.mapping.Name,"legalName");assert.equal(preview.rows[0].before.legalName,"Atomic LLC");assert.equal(preview.rows[0].before.status,"lead");const result=await commitCsvUpdate(actor,{runId:preview.runId,expectedPreviewRevision:1});assert.equal(result.created,1);const saved=await getDealForDocument(actor,target.id);assert.equal(saved.legalName,"Atomic Renamed LLC");assert.equal(saved.status,"new_application");assert.equal(saved.version,target.version+1);await commitCsvUpdate(actor,{runId:preview.runId,expectedPreviewRevision:1});assert.equal((await getDealForDocument(actor,target.id)).version,saved.version)})

test("MIC-173 rolls back a stale worker's deal update when its commit token was reclaimed",async()=>{const source=(await listImportRegistry(actor)).sources[0],batch=(await listImportRegistry(actor)).batches[0],target=(await createDeal(actor,{idempotencyKey:"reclaimed-update",legalName:"Original Reclaim LLC"})).deal,preview=await previewCsvUpdate(actor,{sourceId:source.id,batchId:batch.id,filename:"reclaimed.csv",bytes:Buffer.from(`dealId,expectedVersion,legalName\n${target.id},${target.version},Stale Worker LLC`)}),row=preview.rows[0],staleToken=await beginCommit(actor.workspaceId,preview.runId,1);assert.ok(staleToken);await getDatabase().prepare("UPDATE import_runs SET lease_expires_at=? WHERE id=?").run("2000-01-01T00:00:00.000Z",preview.runId);const activeToken=await beginCommit(actor.workspaceId,preview.runId,1);assert.ok(activeToken);assert.notEqual(activeToken,staleToken);await assert.rejects(()=>applyBulkDealUpdate(actor,target.id,{expectedVersion:target.version,changes:{legalName:"Stale Worker LLC"},reason:"stale worker regression",transactionCheckpoint:async(database)=>{if(!await recordRowResultInTransaction(database,actor.workspaceId,preview.runId,row.id,"updated",target.id,null,staleToken!))throw new Error("stale worker fenced")}}),/stale worker fenced/);const unchanged=await getDealForDocument(actor,target.id);assert.equal(unchanged.legalName,"Original Reclaim LLC");assert.equal(unchanged.version,target.version)})

test("MIC-167 validates folder URLs, pagination/denied files, and streamed download limits",async()=>{assert.equal(parseDriveFolderId("https://drive.google.com/drive/folders/abcdefghij123"),"abcdefghij123");assert.throws(()=>parseDriveFolderId("https://drive.google.com/open?id=../../etc/passwd"));const originalFetch=globalThis.fetch;let page=0;globalThis.fetch=async()=>new Response(JSON.stringify(page++===0?{nextPageToken:"next",files:[{id:"a",name:"denied.pdf",mimeType:"application/pdf",capabilities:{canDownload:false}}]}:{files:[{id:"b",name:"leads.csv",mimeType:"text/csv",size:"10",capabilities:{canDownload:true}}]}),{status:200,headers:{"content-type":"application/json"}})
  try{const first=await listDriveFolder("folder12345",{accessToken:"token"});assert.equal(first.files[0].canDownload,false);const second=await listDriveFolder("folder12345",{accessToken:"token"},{pageToken:first.nextPageToken!});assert.equal(second.files[0].name,"leads.csv");await assert.rejects(()=>downloadDriveFile({...first.files[0],state:"listed"},{accessToken:"token"}),(error:{code?:string})=>error.code==="drive_file_denied")}finally{globalThis.fetch=originalFetch}})

test("MIC-167 uses OAuth state, verified offline scope, and refreshes credentials",async()=>{const started=await beginDriveOAuth(actor,"https://drive.google.com/drive/folders/abcdefghij123"),url=new URL(started.authorizationUrl),state=url.searchParams.get("state")!;assert.equal(url.searchParams.get("access_type"),"offline");assert.equal(url.searchParams.get("scope"),"https://www.googleapis.com/auth/drive.readonly");const originalFetch=globalThis.fetch;let request=0;globalThis.fetch=async()=>{request++;if(request===1)return new Response(JSON.stringify({access_token:"access",refresh_token:"refresh",expires_in:3600,scope:"https://www.googleapis.com/auth/drive.readonly"}),{status:200});if(request===2)return new Response(JSON.stringify({id:"abcdefghij123",name:"Approved folder",mimeType:"application/vnd.google-apps.folder"}),{status:200});return new Response(JSON.stringify({access_token:"renewed",expires_in:7200}),{status:200})};try{const status=await completeDriveOAuth(actor,{state,code:"authorization-code"});assert.equal(status.connected,true);await assert.rejects(()=>completeDriveOAuth(actor,{state,code:"authorization-code"}),(error:{code?:string})=>error.code==="drive_oauth_state");const renewed=await refreshDriveCredential({accessToken:"expired",refreshToken:"refresh",expiresAt:"2000-01-01T00:00:00.000Z"});assert.equal(renewed.accessToken,"renewed")}finally{globalThis.fetch=originalFetch;await removeDriveConnection(actor.workspaceId)}})

test("MIC-167 resumes downloaded Drive checkpoints without listing or overwriting them",async()=>{const registry=await listImportRegistry(actor),source=registry.sources[0],batch=registry.batches[0],preview=await previewSpreadsheetImport(actor,{sourceId:source.id,batchId:batch.id,filename:"drive-resume.csv",bytes:Buffer.from("Business Name\nDrive Resume LLC")});await commitSpreadsheetImport(actor,{runId:preview.runId,expectedPreviewRevision:1});await recordDriveTransfer({workspaceId:actor.workspaceId,runId:preview.runId,fileId:"drive-file-complete",name:"Drive Resume LLC/statement.pdf",state:"downloaded",checksum:"abc123",byteLength:321});await removeDriveConnection(actor.workspaceId);const originalFetch=globalThis.fetch;let requests=0;globalThis.fetch=async()=>{requests++;throw new Error("checkpointed files must not reach Drive")};try{const resumed=await applyDriveDocuments(actor,{runId:preview.runId,confirmations:[{fileId:"drive-file-complete",rowId:preview.rows[0].id,category:"statement"}]});assert.equal(resumed.results[0].state,"downloaded");assert.equal(resumed.results[0].size,321);assert.equal(requests,0);await recordDriveTransfer({workspaceId:actor.workspaceId,runId:preview.runId,fileId:"drive-file-complete",name:"Removed file",state:"removed",message:"late retry"});assert.equal((await driveTransfersForRun(actor.workspaceId,preview.runId)).get("drive-file-complete")?.state,"downloaded")}finally{globalThis.fetch=originalFetch}})

test("MIC-119 staged PII is admin-session only at the service boundary",async()=>{const rep={...actor,userId:ids.repAUser,membershipId:ids.repA,role:"rep" as const};await assert.rejects(()=>listImportRegistry(rep),(error:{code?:string})=>error.code==="permission_denied")})
