import test,{before,after} from 'node:test'
import assert from 'node:assert/strict'
import {randomUUID} from 'node:crypto'
import {createPostgresTestDatabase} from './helpers/postgres-test-db.mjs'
import {getDatabase,closeDatabaseForTests,nowIso} from '../src/lib/mca/db'
import {createWorkspaceWithAdmin} from '../src/lib/mca/workspaces'
import {authContinuation} from '../src/lib/mca/auth-navigation'
import {signupStripeProvider as provider} from './helpers/signup-stripe-provider'
let database:Awaited<ReturnType<typeof createPostgresTestDatabase>>
before(async()=>{database=await createPostgresTestDatabase('stripe_first');process.env.DATABASE_URL=database.databaseUrl;Object.assign(process.env,{MCA_STRIPE_BILLING_ENABLED:'true',MCA_STRIPE_MODE:'test',STRIPE_SECRET_KEY:'rk_test_fixture',STRIPE_BASE_PRICE_ID:'price_base',STRIPE_ADDITIONAL_SEAT_PRICE_ID:'price_seats',STRIPE_BILLING_WEBHOOK_SECRET:'whsec_fixture',MCA_APP_ORIGIN:'http://localhost:3000',MCA_TRIAL_ABUSE_LIMITS_ENABLED:'true'})})
after(async()=>{await closeDatabaseForTests();await database?.close()})

async function workspace(email=`${randomUUID()}@example.test`){const f=await createWorkspaceWithAdmin({workspaceName:randomUUID(),adminName:'Owner',adminEmail:email,password:'Synthetic password 99!',role:'admin'});await getDatabase().prepare("UPDATE company_subscription_state SET legacy_exempt=0,state_kind='customer' WHERE workspace_id=?").run(f.workspaceId);await getDatabase().prepare('INSERT INTO workspace_owners(workspace_id,membership_id,updated_at) VALUES (?,?,?)').run(f.workspaceId,f.membershipId,nowIso());return f}
test('email verification preserves activation but rejects external continuations',()=>{assert.equal(authContinuation('/activate'),'/activate');assert.equal(authContinuation('https://attacker.test/activate'),'/onboarding')})
test('card setup creates no subscription and retries reuse the session',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),first=await s.beginSignupCheckout(undefined,p.client),retry=await s.beginSignupCheckout(first.token,p.client);assert.equal(retry.url,first.url);assert.equal(p.calls.setups,1);assert.equal(p.calls.setup.mode,'setup');assert.equal(p.calls.subscriptions,0);assert.equal(p.calls.customers,0)})
test('matching verified identity and token activate exactly one trial',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),first=await s.beginSignupCheckout(undefined,p.client);await s.completeSignupSetup(p.complete(),p.client);await assert.rejects(()=>s.readSignupIntent('invalid'),/expired|invalid/i);const f=await workspace(p.email),ctx={workspaceId:f.workspaceId,userId:f.userId,email:p.email};await assert.rejects(()=>s.activateSignup(first.token,{...ctx,email:'other@example.test'},p.client),/email/i);assert.equal(p.calls.subscriptions,0);assert.equal((await s.activateSignup(first.token,ctx,p.client)).status,'active');assert.equal(p.calls.sub.trial_period_days,14);assert.deepEqual(p.calls.sub.items,[{price:'price_base',quantity:1}]);assert.equal((await s.activateSignup(first.token,ctx,p.client)).status,'active');assert.equal(p.calls.subscriptions,1);const other=await workspace();await assert.rejects(()=>s.activateSignup(first.token,{...ctx,workspaceId:other.workspaceId,userId:other.userId},p.client),/claimed|company/i)})
test('incomplete or expired setup cannot activate',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),start=await s.beginSignupCheckout(undefined,p.client),f=await workspace();await assert.rejects(()=>s.activateSignup(start.token,{workspaceId:f.workspaceId,userId:f.userId,email:p.email},p.client),/card|complete/i);await getDatabase().prepare("UPDATE company_signup_intents SET expires_at='2000-01-01' WHERE token_hash=?").run((await import('../src/lib/mca/crypto')).hashOpaqueToken(start.token));await assert.rejects(()=>s.readSignupIntent(start.token),/expired/i);assert.equal(p.calls.subscriptions,0)})
test('repeat trial eligibility requires paid confirmation rather than an automatic charge',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),start=await s.beginSignupCheckout(undefined,p.client);await s.completeSignupSetup(p.complete(),p.client);const f=await workspace(p.email),old=await workspace();await getDatabase().prepare('INSERT INTO company_trial_grants (workspace_id,stripe_subscription_id,owner_user_id,owner_email,email_domain,trial_started_at,created_at) VALUES (?,?,?,?,?,?,?)').run(old.workspaceId,'sub_previous',f.userId,p.email,'example.test',nowIso(),nowIso());assert.equal((await s.activateSignup(start.token,{workspaceId:f.workspaceId,userId:f.userId,email:p.email},p.client)).status,'paid_required');assert.equal(p.calls.subscriptions,0)})
test('recovery email explains activation rather than showing an operations alert',async()=>{const {renderEmailContent}=await import('../src/lib/mca/operations/email-transport');const result=renderEmailContent({template:'signup_activation',recipient:'owner@example.test',actionUrl:'https://fundlane.io/signup-resume?token=synthetic',expiresAt:'2030-01-01'});assert.equal(result.subject,'Finish setting up Fundlane');assert.match(result.text,/no subscription|has not started a subscription/i);assert.match(result.text,/Finish signup/);assert.doesNotMatch(result.text,/platform status/)})
test('signup mutations reject missing and foreign browser origins',async()=>{const s=await import('../src/lib/mca/stripe-first-signup');for(const origin of [undefined,'https://attacker.test'])assert.throws(()=>s.assertSignupOrigin(new Request('https://fundlane.io/api/billing/signup-checkout',{method:'POST',headers:origin?{origin}:{}})),/origin/i);s.assertSignupOrigin(new Request('https://fundlane.io/api/billing/signup-checkout',{method:'POST',headers:{origin:'https://fundlane.io'}}))})
test('signup email cannot be substituted after Stripe saved a card',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),start=await s.beginSignupCheckout(undefined,p.client);await assert.rejects(()=>s.requireSignupEmail(start.token,p.email),/card/i);await s.completeSignupSetup(p.complete(),p.client);await assert.rejects(()=>s.requireSignupEmail(start.token,'attacker@example.test'),/email/i);assert.equal((await s.requireSignupEmail(start.token,p.email.toUpperCase())).checkout_email,p.email)})
test('mismatched setup metadata and an unsuccessful card cannot become ready',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),start=await s.beginSignupCheckout(undefined,p.client),sessionId=p.complete(),session=p.sessions.get(sessionId)!;const metadata=session.metadata;session.metadata={fundlane_signup_intent:'other'};await assert.rejects(()=>s.completeSignupSetup(sessionId,p.client),/verified/i);session.metadata=metadata;session.setup_intent={livemode:false,status:'requires_payment_method',payment_method:null};await assert.rejects(()=>s.completeSignupSetup(sessionId,p.client),/card/i);assert.equal((await s.readSignupIntent(start.token)).state,'pending');assert.equal(p.calls.subscriptions,0)})
test('interrupted subscription reconciliation recovers the created trial without creating another',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),start=await s.beginSignupCheckout(undefined,p.client);await s.completeSignupSetup(p.complete(),p.client);const f=await workspace(p.email),context={workspaceId:f.workspaceId,userId:f.userId,email:p.email};const list=p.client.invoices.list;p.client.invoices.list=(async()=>{throw new Error('Synthetic reconciliation outage')}) as typeof list;await assert.rejects(()=>s.activateSignup(start.token,context,p.client),/outage/);assert.equal(p.calls.subscriptions,1);p.client.invoices.list=list;assert.equal((await s.activateSignup(start.token,context,p.client)).status,'active');assert.equal(p.calls.subscriptions,1);assert.equal((await (await import('../src/lib/mca/company-access')).getCompanyAccess(f.workspaceId)).seatLimit,1)})
test('signed setup event processing retries recovery mail and duplicate events never start billing',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),start=await s.beginSignupCheckout(undefined,p.client),sessionId=p.complete();const {processStripeBillingEvent}=await import('../src/lib/mca/billing');const event={id:`evt_${randomUUID()}`,type:'checkout.session.completed',livemode:false,data:{object:{id:sessionId,mode:'setup',customer:null}}} as Parameters<typeof processStripeBillingEvent>[0];const previous=global.fetch;process.env.MCA_EMAIL_WEBHOOK_URL='http://localhost/email-fixture';let attempts=0;const deliveries:Array<{body:string;key:string}>=[];global.fetch=(async(_url,init)=>{attempts++;deliveries.push({body:String(init?.body),key:new Headers(init?.headers).get('idempotency-key')!});return new Response('',{status:attempts===1?503:200})}) as typeof fetch;try{await assert.rejects(()=>processStripeBillingEvent(event,p.client),/email provider/i);assert.equal((await s.readSignupIntent(start.token)).state,'ready');assert.deepEqual(await processStripeBillingEvent(event,p.client),{signupReady:true});await processStripeBillingEvent(event,p.client);assert.equal(attempts,2);assert.equal(deliveries[0].key,deliveries[1].key);assert.equal(deliveries[0].body,deliveries[1].body);assert.equal(p.calls.subscriptions,0);const message=JSON.parse(deliveries[1].body);assert.equal(message.recipient,p.email);assert.equal(new URL(message.actionUrl).searchParams.get('token'),start.token)}finally{global.fetch=previous;delete process.env.MCA_EMAIL_WEBHOOK_URL}})
test('concurrent activation uses one durable Stripe customer and subscription',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),start=await s.beginSignupCheckout(undefined,p.client);await s.completeSignupSetup(p.complete(),p.client);const f=await workspace(p.email),context={workspaceId:f.workspaceId,userId:f.userId,email:p.email};const results=await Promise.all([s.activateSignup(start.token,context,p.client),s.activateSignup(start.token,context,p.client)]);assert.ok(results.every(r=>r.status==='active'));assert.equal(p.calls.customers,1);assert.equal(p.calls.subscriptions,1)})
test('lost Checkout response preserves identical parameters and the same session on retry',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),token=await s.createSignupIntent(),create=p.client.checkout.sessions.create;let once=true;let original:unknown;p.client.checkout.sessions.create=(async(...args:Parameters<typeof create>)=>{const result=await create(...args);if(once){once=false;original=args;throw new Error('Synthetic lost response')};assert.deepEqual(args,original);return result}) as typeof create;await assert.rejects(()=>s.beginSignupCheckout(token,p.client),/lost response/);await s.beginSignupCheckout(token,p.client);assert.equal(p.calls.setups,1);assert.equal(p.calls.subscriptions,0)})
test('ordinary billing Checkout cannot race a pending signup activation',async()=>{const s=await import('../src/lib/mca/stripe-first-signup'),p=provider(),start=await s.beginSignupCheckout(undefined,p.client);await s.completeSignupSetup(p.complete(),p.client);const f=await workspace(p.email),intent=await s.readSignupIntent(start.token);await getDatabase().prepare('UPDATE company_signup_intents SET workspace_id=?,user_id=? WHERE id=?').run(f.workspaceId,f.userId,intent.id);const {createBillingCheckout}=await import('../src/lib/mca/billing');await assert.rejects(()=>createBillingCheckout(f.workspaceId,1,true,p.client),{code:'signup_activation_pending'});assert.equal(p.calls.customers,0);assert.equal(p.calls.setups,1)})
