import test from "node:test"
import assert from "node:assert/strict"
import { EventEmitter } from "node:events"
import { BrowserVoice } from "../src/lib/mca/voice/browser"
class Call extends EventEmitter { rejected=0; disconnected=0; accepted=0; parameters={From:"+15555550101"}; accept(){this.accepted++;this.emit("accept")}reject(){this.rejected++;this.emit("reject")}disconnect(){this.disconnected++;this.emit("disconnect")}}
class Device extends EventEmitter {destroyed=0;token="";next:Promise<Call>=Promise.resolve(new Call()); async register(){this.emit("registered")}async connect(){return this.next}updateToken(token:string){this.token=token}destroy(){this.destroyed++}}
function harness(){const device=new Device();const states:string[]=[];let presence=0;let canceled=0; const voice=new BrowserVoice({createDevice:()=>device,token:async()=>({token:"synthetic"}),presence:async enabled=>{presence+=enabled?1:-1},intent:async()=>({intentId:"intent"}),cancelIntent:async()=>{canceled++},onState:s=>states.push(s.state)});return {voice,device,states,get presence(){return presence},get canceled(){return canceled}}}
test("register, incoming answer/disconnect, reject and disable clean up",async()=>{const h=harness();await h.voice.enable();assert.equal(h.voice.snapshot.state,"ready");const call=new Call();h.device.emit("incoming",call);assert.equal(h.voice.snapshot.state,"incoming");h.voice.answer();assert.equal(call.accepted,1);assert.equal(h.voice.snapshot.state,"connected");await h.voice.end();assert.equal(call.disconnected,1);const second=new Call();h.device.emit("incoming",second);await h.voice.end();assert.equal(second.rejected,1);await h.voice.disable();assert.equal(h.device.destroyed,1);assert.equal(h.voice.snapshot.state,"disabled")})
test("cancel while connect pending disconnects late call and cancels server intent",async()=>{const h=harness();await h.voice.enable();let resolve!:(v:Call)=>void;h.device.next=new Promise(r=>{resolve=r});const pending=h.voice.dial("deal-a");await new Promise(r=>setImmediate(r));await h.voice.end();const late=new Call();resolve(late);await pending;assert.equal(late.disconnected,1);assert.equal(h.canceled,1);assert.equal(h.voice.snapshot.state,"ready")})
test("disable during token load cannot resurrect device",async()=>{let resolve!:(v:{token:string})=>void;const device=new Device();const voice=new BrowserVoice({createDevice:()=>device,token:()=>new Promise(r=>{resolve=r}),presence:async()=>{},intent:async()=>({intentId:"x"}),cancelIntent:async()=>{},onState:()=>{}});const enabling=voice.enable();await voice.disable();resolve({token:"late"});await enabling;assert.equal(voice.snapshot.state,"disabled");assert.equal(device.listenerCount("incoming"),0)})
test("busy incoming rejects, refresh errors fail closed, manual retry works",async()=>{const h=harness();await h.voice.enable();const first=new Call();h.device.emit("incoming",first);const second=new Call();h.device.emit("incoming",second);assert.equal(second.rejected,1);h.device.emit("error",new Error("secret provider response"));await new Promise(r=>setImmediate(r));assert.equal(h.voice.snapshot.state,"error");assert.ok(!h.voice.snapshot.message.includes("secret"));await h.voice.enable();assert.equal(h.voice.snapshot.state,"ready");await h.voice.disable()})
