import { notFound } from "next/navigation"
import Link from "next/link"
import { ArrowLeft, Construction } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

const sections: Record<string, { title: string; description: string; milestone: string }> = {
  submissions: { title: "Submissions", description: "Funder submissions and their status will live here.", milestone: "Deal and application workflow" }, offers: { title: "Offers", description: "Compare received funding offers and terms here.", milestone: "Offer management" }, advances: { title: "Advances", description: "Funded advances and balances will live here.", milestone: "Servicing workflow" }, renewals: { title: "Renewals", description: "Renewal eligibility and follow-up will live here.", milestone: "Renewal workflow" }, payments: { title: "Payments", description: "Payment activity will appear here when the payment workflow is delivered.", milestone: "Payments and commissions" }, reports: { title: "Reports", description: "Workspace reports will appear here when reporting is delivered.", milestone: "Reporting and analytics" },
}

export default async function FutureSectionPage({ params }: { params: Promise<{ section: string }> }) { const { section } = await params; const page = sections[section]; if (!page) notFound(); return <div className="px-4 lg:px-6"><div className="mb-6"><h1 className="text-2xl font-semibold tracking-tight">{page.title}</h1><p className="mt-1 text-sm text-muted-foreground">{page.description}</p></div><Card><CardContent className="flex min-h-80 flex-col items-center justify-center p-8 text-center"><span className="rounded-xl bg-muted p-3"><Construction className="size-6 text-muted-foreground" /></span><h2 className="mt-4 text-lg font-semibold">Planned for {page.milestone}</h2><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">Navigation and access controls are ready. The workflow itself is scheduled for a later milestone and no production data is shown yet.</p><Button asChild variant="outline" className="mt-5"><Link href="/dashboard"><ArrowLeft /> Back to home</Link></Button></CardContent></Card></div> }
