import "server-only"

import { isDocumentReady } from "../documents/contracts"

import { createHash, randomBytes } from "node:crypto"
import { basename, extname } from "node:path"
import { recordAuditEvent } from "../db"
import type { DealActor } from "../deals/schema"
import { storeDocument } from "../documents/service"
import { AppError } from "../errors"
import { normalizedMerchantName } from "./archive"
import { assertArchiveCategory } from "./category"
import type { ArchiveCategory, ArchiveEntryPreview, DriveFileResult, ImportPreview } from "./contracts"
import { downloadDriveFile, driveAuthorizationUrl, exchangeDriveAuthorizationCode, listDriveFolder, parseDriveFolderId, refreshDriveCredential, revokeDriveCredential, verifyDriveFolder, type DriveListedFile } from "./drive"
import { consumeDriveOauthState, driveConnectionStatus, driveTransfersForRun, findImportRow, findPreview, loadDriveConnection, recordDriveTransfer, removeDriveConnection, saveDriveConnection, saveDriveOauthState } from "./repository"
import { previewSpreadsheetImport } from "./service"

const FOLDER_MIME = "application/vnd.google-apps.folder"
const SHEET_MIMES = new Set(["text/csv","application/vnd.google-apps.spreadsheet"])
const MAX_TREE_FILES = 2_000

function requireAdmin(actor: DealActor): void { if (!actor.role || !["admin","super_admin"].includes(actor.role)) throw new AppError(403,"permission_denied","Only workspace administrators can manage the Google Drive connection.") }
const stateHash=(value:string)=>createHash("sha256").update(value).digest("hex")

export async function beginDriveOAuth(actor:DealActor,folderUrl:string):Promise<{authorizationUrl:string}>{requireAdmin(actor);const folderId=parseDriveFolderId(folderUrl),state=randomBytes(32).toString("base64url");await saveDriveOauthState(actor.workspaceId,stateHash(state),folderId,new Date(Date.now()+10*60_000).toISOString());return{authorizationUrl:driveAuthorizationUrl(state)}}
export async function completeDriveOAuth(actor:DealActor,input:{state:string;code:string}):Promise<Awaited<ReturnType<typeof driveConnectionStatus>>>{requireAdmin(actor);const pending=await consumeDriveOauthState(actor.workspaceId,stateHash(input.state));if(!pending)throw new AppError(403,"drive_oauth_state","The Google Drive authorization link expired or was already used. Start again.");const grant=await exchangeDriveAuthorizationCode(input.code),folder=await verifyDriveFolder(pending.folderId,grant.credential);await saveDriveConnection(actor.workspaceId,folder,grant.credential,grant.scope);await recordAuditEvent({context:actor,action:"drive.connected",resourceType:"drive_connection",resourceId:folder.id,metadata:{scope:grant.scope},correlationId:actor.correlationId});return driveConnectionStatus(actor.workspaceId)}
export async function getDriveStatus(actor:DealActor):Promise<Awaited<ReturnType<typeof driveConnectionStatus>>>{return driveConnectionStatus(actor.workspaceId)}

async function activeConnection(actor:DealActor){const connection=await loadDriveConnection(actor.workspaceId);if(!connection)throw new AppError(503,"drive_not_connected","Connect Google Drive before importing a folder.");if(connection.credential.expiresAt&&Date.parse(connection.credential.expiresAt)<=Date.now()+60_000){connection.credential=await refreshDriveCredential(connection.credential);await saveDriveConnection(actor.workspaceId,{id:connection.folderId,name:connection.folderName},connection.credential,connection.scope)}return connection}
async function listTree(actor:DealActor):Promise<DriveListedFile[]>{const connection=await activeConnection(actor);const queue:[string,string][]=[[connection.folderId,""]];const output:DriveListedFile[]=[]
  while(queue.length){const [folderId,prefix]=queue.shift()!;let pageToken:string|undefined
    do{const page=await listDriveFolder(folderId,connection.credential,{pageToken,pageSize:200});for(const file of page.files){if(output.length>=MAX_TREE_FILES)throw new AppError(422,"drive_file_limit",`Google Drive packages may contain at most ${MAX_TREE_FILES.toLocaleString()} items.`);const item={...file,name:`${prefix}${file.name}`};output.push(item);if(file.mimeType===FOLDER_MIME)queue.push([file.id,`${item.name}/`])}pageToken=page.nextPageToken??undefined}while(pageToken)}return output}

export async function listDrivePackage(actor:DealActor):Promise<DriveListedFile[]>{return listTree(actor)}
export async function previewDrivePackage(actor:DealActor,input:{sourceId:string;batchId:string;assignmentPool?:string[];useAiMapping?:boolean}):Promise<{preview:ImportPreview;files:DriveListedFile[];matches:ArchiveEntryPreview[]}>{const connection=await activeConnection(actor);const files=await listTree(actor);const sheets=files.filter((file)=>SHEET_MIMES.has(file.mimeType)||/\.csv$/i.test(file.name))
  if(!sheets.length)throw new AppError(422,"drive_spreadsheet_missing","The granted folder does not contain a supported spreadsheet.");if(sheets.length>1)throw new AppError(422,"drive_spreadsheet_ambiguous","The folder contains multiple spreadsheets. Keep one roster spreadsheet or choose a file explicitly.")
  const downloaded=await downloadDriveFile(sheets[0],connection.credential)
  const preview=await previewSpreadsheetImport(actor,{sourceId:input.sourceId,batchId:input.batchId,filename:downloaded.filename,bytes:downloaded.bytes,assignmentPool:input.assignmentPool,useAiMapping:input.useAiMapping})
  await recordDriveTransfer({workspaceId:actor.workspaceId,runId:preview.runId,fileId:sheets[0].id,name:sheets[0].name,state:"downloaded",checksum:sheets[0].md5Checksum,byteLength:downloaded.bytes.byteLength})
  for(const file of files.filter((item)=>item.id!==sheets[0].id&&item.mimeType!==FOLDER_MIME)){const state=!file.canDownload?"denied":file.size!==null&&file.size>25*1024*1024?"too_large":"listed";await recordDriveTransfer({workspaceId:actor.workspaceId,runId:preview.runId,fileId:file.id,name:file.name,state,message:state==="denied"?"The connected account cannot download this file.":state==="too_large"?"File exceeds the 25 MiB transfer limit.":undefined,checksum:file.md5Checksum})}
  const rowNames=new Map<string,string[]>();for(const row of preview.rows){const name=normalizedMerchantName(row.application.legalName??row.application.dbaName??"");if(name)rowNames.set(name,[...(rowNames.get(name)??[]),row.id])}const matches:ArchiveEntryPreview[]=files.filter((file)=>file.id!==sheets[0].id&&file.mimeType!==FOLDER_MIME).map((file)=>{const parts=file.name.split("/");const normalizedFolder=normalizedMerchantName(parts.length>1?parts[0]:basename(file.name,extname(file.name)));const candidateRowIds=rowNames.get(normalizedFolder)??[];return{archiveName:"Google Drive",path:file.name,normalizedFolder,byteLength:file.size??0,category:/statement/i.test(file.name)?"statement":/application/i.test(file.name)?"application":"other_stip",candidateRowIds,state:candidateRowIds.length===1?"exact":candidateRowIds.length>1?"ambiguous":"unmatched"}})
  await recordAuditEvent({context:actor,action:"drive.package_previewed",resourceType:"import_run",resourceId:preview.runId,metadata:{fileCount:files.length,folderId:connection.folderId},correlationId:actor.correlationId});return{preview,files,matches}}

function documentMime(file:DriveListedFile):string{if(["application/pdf","image/png","image/jpeg"].includes(file.mimeType))return file.mimeType;const extension=extname(file.name).toLocaleLowerCase();if(extension===".pdf")return"application/pdf";if(extension===".png")return"image/png";if(extension===".jpg"||extension===".jpeg")return"image/jpeg";throw new AppError(415,"unsupported_document_type",`${file.name} is not a supported document.`)}

export async function applyDriveDocuments(actor:DealActor,input:{runId:string;confirmations:Array<{fileId:string;rowId:string;category:ArchiveCategory}>}):Promise<{results:DriveFileResult[]}>{for(const confirmation of input.confirmations)assertArchiveCategory(confirmation.category);const preview=await findPreview(actor.workspaceId,input.runId);if(!preview||preview.state!=="completed")throw new AppError(409,"import_not_completed","Commit the roster before transferring confirmed Drive documents.");const validRows=new Set(preview.rows.map((row)=>row.id));for(const confirmation of input.confirmations)if(!validRows.has(confirmation.rowId))throw new AppError(404,"import_row_not_found","A Drive match references an unavailable import row.");const checkpoints=await driveTransfersForRun(actor.workspaceId,input.runId),pending=input.confirmations.filter((confirmation)=>checkpoints.get(confirmation.fileId)?.state!=="downloaded"),results:DriveFileResult[]=input.confirmations.flatMap((confirmation)=>{const checkpoint=checkpoints.get(confirmation.fileId);return checkpoint?.state==="downloaded"?[{id:checkpoint.id,name:checkpoint.name,mimeType:"",size:checkpoint.byteLength,md5Checksum:checkpoint.checksum,canDownload:true,state:"downloaded" as const,message:checkpoint.message}]:[]});if(!pending.length)return{results};const connection=await activeConnection(actor),files=await listTree(actor),byId=new Map(files.map((file)=>[file.id,file]))
  for(const confirmation of pending){const file=byId.get(confirmation.fileId);if(!file){const missing={id:confirmation.fileId,name:"Removed file",mimeType:"",size:null,md5Checksum:null,canDownload:false,state:"removed" as const,message:"The file was removed after preview."};await recordDriveTransfer({workspaceId:actor.workspaceId,runId:input.runId,fileId:missing.id,name:missing.name,state:missing.state,message:missing.message});results.push(missing);continue}const row=await findImportRow(actor.workspaceId,input.runId,confirmation.rowId);if(!row?.dealId)throw new AppError(409,"import_row_uncommitted","The matched row does not have a committed deal.")
    try{const downloaded=await downloadDriveFile(file,connection.credential);const document=await storeDocument(actor,{dealId:row.dealId,idempotencyKey:`drive:${input.runId}:${file.id}`,filename:basename(downloaded.filename),mimeType:documentMime(file),bytes:downloaded.bytes,category:confirmation.category,source:"google_drive",sourceReference:`drive:${file.id}`});const result={...file,state:"downloaded" as const,message:isDocumentReady(document.processingState)?undefined:`Stored with ${document.processingState}; processing can be retried.`};await recordDriveTransfer({workspaceId:actor.workspaceId,runId:input.runId,fileId:file.id,name:file.name,state:result.state,message:result.message,checksum:file.md5Checksum,byteLength:downloaded.bytes.byteLength});results.push(result)}catch(error){const code=error instanceof AppError?error.code:"drive_download_failed",state=code==="drive_file_denied"?"denied" as const:code==="drive_file_removed"?"removed" as const:code==="drive_file_too_large"?"too_large" as const:"unsupported" as const;const result={...file,state,message:error instanceof Error?error.message:"Drive transfer failed."};await recordDriveTransfer({workspaceId:actor.workspaceId,runId:input.runId,fileId:file.id,name:file.name,state,message:result.message,checksum:file.md5Checksum});results.push(result)}}return{results}}

export async function disconnectDrive(actor:DealActor):Promise<void>{requireAdmin(actor);const connection=await loadDriveConnection(actor.workspaceId);if(!connection)return;await revokeDriveCredential(connection.credential);await removeDriveConnection(actor.workspaceId);await recordAuditEvent({context:actor,action:"drive.revoked",resourceType:"drive_connection",resourceId:connection.id,metadata:{},correlationId:actor.correlationId})}
